import type { CRDocument } from '../types';
import { SET_BLOCKS } from './sets';

// Generated by scripts/katameros/gen.ts — 366 Coptic days (1742 AM, leap-year shape).
// Sundays computed from 1 Tout 1742 AM = Thu Sep 11, 2025; Great Fast from Orthodox Easter 2026-04-12.
const byKey: Record<string, CRDocument> = {};
byKey["tout-1"] = { id: "katameros-tout-1", title: {"en":"1 Tout","ar":"1 توت"}, subtitle: { en: "September 11, 2025", ar: "September 11, 2025" }, blocks: SET_BLOCKS[1] };
byKey["tout-2"] = { id: "katameros-tout-2", title: {"en":"2 Tout","ar":"2 توت"}, subtitle: { en: "September 12, 2025", ar: "September 12, 2025" }, blocks: SET_BLOCKS[2] };
byKey["tout-3"] = { id: "katameros-tout-3", title: {"en":"3 Tout","ar":"3 توت"}, subtitle: { en: "September 13, 2025", ar: "September 13, 2025" }, blocks: SET_BLOCKS[54] };
byKey["tout-4"] = { id: "katameros-tout-4", title: {"en":"4 Tout","ar":"4 توت"}, subtitle: { en: "September 14, 2025", ar: "September 14, 2025" }, blocks: SET_BLOCKS[3] };
byKey["tout-5"] = { id: "katameros-tout-5", title: {"en":"5 Tout","ar":"5 توت"}, subtitle: { en: "September 15, 2025", ar: "September 15, 2025" }, blocks: SET_BLOCKS[39] };
byKey["tout-6"] = { id: "katameros-tout-6", title: {"en":"6 Tout","ar":"6 توت"}, subtitle: { en: "September 16, 2025", ar: "September 16, 2025" }, blocks: SET_BLOCKS[3] };
byKey["tout-7"] = { id: "katameros-tout-7", title: {"en":"7 Tout","ar":"7 توت"}, subtitle: { en: "September 17, 2025", ar: "September 17, 2025" }, blocks: SET_BLOCKS[54] };
byKey["tout-8"] = { id: "katameros-tout-8", title: {"en":"8 Tout","ar":"8 توت"}, subtitle: { en: "September 18, 2025", ar: "September 18, 2025" }, blocks: SET_BLOCKS[3] };
byKey["tout-9"] = { id: "katameros-tout-9", title: {"en":"9 Tout","ar":"9 توت"}, subtitle: { en: "September 19, 2025", ar: "September 19, 2025" }, blocks: SET_BLOCKS[23] };
byKey["tout-10"] = { id: "katameros-tout-10", title: {"en":"10 Tout","ar":"10 توت"}, subtitle: { en: "September 20, 2025", ar: "September 20, 2025" }, blocks: SET_BLOCKS[39] };
byKey["tout-11"] = { id: "katameros-tout-11", title: {"en":"11 Tout","ar":"11 توت"}, subtitle: { en: "September 21, 2025", ar: "September 21, 2025" }, blocks: SET_BLOCKS[44] };
byKey["tout-12"] = { id: "katameros-tout-12", title: {"en":"12 Tout","ar":"12 توت"}, subtitle: { en: "September 22, 2025", ar: "September 22, 2025" }, blocks: SET_BLOCKS[15] };
byKey["tout-13"] = { id: "katameros-tout-13", title: {"en":"13 Tout","ar":"13 توت"}, subtitle: { en: "September 23, 2025", ar: "September 23, 2025" }, blocks: SET_BLOCKS[18] };
byKey["tout-14"] = { id: "katameros-tout-14", title: {"en":"14 Tout","ar":"14 توت"}, subtitle: { en: "September 24, 2025", ar: "September 24, 2025" }, blocks: SET_BLOCKS[57] };
byKey["tout-15"] = { id: "katameros-tout-15", title: {"en":"15 Tout","ar":"15 توت"}, subtitle: { en: "September 25, 2025", ar: "September 25, 2025" }, blocks: SET_BLOCKS[29] };
byKey["tout-16"] = { id: "katameros-tout-16", title: {"en":"16 Tout","ar":"16 توت"}, subtitle: { en: "September 26, 2025", ar: "September 26, 2025" }, blocks: SET_BLOCKS[4] };
byKey["tout-17"] = { id: "katameros-tout-17", title: {"en":"17 Tout","ar":"17 توت"}, subtitle: { en: "September 27, 2025", ar: "September 27, 2025" }, blocks: SET_BLOCKS[5] };
byKey["tout-18"] = { id: "katameros-tout-18", title: {"en":"18 Tout","ar":"18 توت"}, subtitle: { en: "September 28, 2025", ar: "September 28, 2025" }, blocks: SET_BLOCKS[6] };
byKey["tout-19"] = { id: "katameros-tout-19", title: {"en":"19 Tout","ar":"19 توت"}, subtitle: { en: "September 29, 2025", ar: "September 29, 2025" }, blocks: SET_BLOCKS[7] };
byKey["tout-20"] = { id: "katameros-tout-20", title: {"en":"20 Tout","ar":"20 توت"}, subtitle: { en: "September 30, 2025", ar: "September 30, 2025" }, blocks: SET_BLOCKS[39] };
byKey["tout-21"] = { id: "katameros-tout-21", title: {"en":"21 Tout","ar":"21 توت"}, subtitle: { en: "October 1, 2025", ar: "October 1, 2025" }, blocks: SET_BLOCKS[8] };
byKey["tout-22"] = { id: "katameros-tout-22", title: {"en":"22 Tout","ar":"22 توت"}, subtitle: { en: "October 2, 2025", ar: "October 2, 2025" }, blocks: SET_BLOCKS[44] };
byKey["tout-23"] = { id: "katameros-tout-23", title: {"en":"23 Tout","ar":"23 توت"}, subtitle: { en: "October 3, 2025", ar: "October 3, 2025" }, blocks: SET_BLOCKS[8] };
byKey["tout-24"] = { id: "katameros-tout-24", title: {"en":"24 Tout","ar":"24 توت"}, subtitle: { en: "October 4, 2025", ar: "October 4, 2025" }, blocks: SET_BLOCKS[29] };
byKey["tout-25"] = { id: "katameros-tout-25", title: {"en":"25 Tout","ar":"25 توت"}, subtitle: { en: "October 5, 2025", ar: "October 5, 2025" }, blocks: SET_BLOCKS[3] };
byKey["tout-26"] = { id: "katameros-tout-26", title: {"en":"26 Tout","ar":"26 توت"}, subtitle: { en: "October 6, 2025", ar: "October 6, 2025" }, blocks: SET_BLOCKS[9] };
byKey["tout-27"] = { id: "katameros-tout-27", title: {"en":"27 Tout","ar":"27 توت"}, subtitle: { en: "October 7, 2025", ar: "October 7, 2025" }, blocks: SET_BLOCKS[19] };
byKey["tout-28"] = { id: "katameros-tout-28", title: {"en":"28 Tout","ar":"28 توت"}, subtitle: { en: "October 8, 2025", ar: "October 8, 2025" }, blocks: SET_BLOCKS[19] };
byKey["tout-29"] = { id: "katameros-tout-29", title: {"en":"29 Tout","ar":"29 توت"}, subtitle: { en: "October 9, 2025", ar: "October 9, 2025" }, blocks: SET_BLOCKS[39] };
byKey["tout-30"] = { id: "katameros-tout-30", title: {"en":"30 Tout","ar":"30 توت"}, subtitle: { en: "October 10, 2025", ar: "October 10, 2025" }, blocks: SET_BLOCKS[18] };
byKey["baba-1"] = { id: "katameros-baba-1", title: {"en":"1 Baba","ar":"1 بابه"}, subtitle: { en: "October 11, 2025", ar: "October 11, 2025" }, blocks: SET_BLOCKS[39] };
byKey["baba-2"] = { id: "katameros-baba-2", title: {"en":"2 Baba","ar":"2 بابه"}, subtitle: { en: "October 12, 2025", ar: "October 12, 2025" }, blocks: SET_BLOCKS[54] };
byKey["baba-3"] = { id: "katameros-baba-3", title: {"en":"3 Baba","ar":"3 بابه"}, subtitle: { en: "October 13, 2025", ar: "October 13, 2025" }, blocks: SET_BLOCKS[18] };
byKey["baba-4"] = { id: "katameros-baba-4", title: {"en":"4 Baba","ar":"4 بابه"}, subtitle: { en: "October 14, 2025", ar: "October 14, 2025" }, blocks: SET_BLOCKS[41] };
byKey["baba-5"] = { id: "katameros-baba-5", title: {"en":"5 Baba","ar":"5 بابه"}, subtitle: { en: "October 15, 2025", ar: "October 15, 2025" }, blocks: SET_BLOCKS[18] };
byKey["baba-6"] = { id: "katameros-baba-6", title: {"en":"6 Baba","ar":"6 بابه"}, subtitle: { en: "October 16, 2025", ar: "October 16, 2025" }, blocks: SET_BLOCKS[39] };
byKey["baba-7"] = { id: "katameros-baba-7", title: {"en":"7 Baba","ar":"7 بابه"}, subtitle: { en: "October 17, 2025", ar: "October 17, 2025" }, blocks: SET_BLOCKS[48] };
byKey["baba-8"] = { id: "katameros-baba-8", title: {"en":"8 Baba","ar":"8 بابه"}, subtitle: { en: "October 18, 2025", ar: "October 18, 2025" }, blocks: SET_BLOCKS[21] };
byKey["baba-9"] = { id: "katameros-baba-9", title: {"en":"9 Baba","ar":"9 بابه"}, subtitle: { en: "October 19, 2025", ar: "October 19, 2025" }, blocks: SET_BLOCKS[18] };
byKey["baba-10"] = { id: "katameros-baba-10", title: {"en":"10 Baba","ar":"10 بابه"}, subtitle: { en: "October 20, 2025", ar: "October 20, 2025" }, blocks: SET_BLOCKS[41] };
byKey["baba-11"] = { id: "katameros-baba-11", title: {"en":"11 Baba","ar":"11 بابه"}, subtitle: { en: "October 21, 2025", ar: "October 21, 2025" }, blocks: SET_BLOCKS[54] };
byKey["baba-12"] = { id: "katameros-baba-12", title: {"en":"12 Baba","ar":"12 بابه"}, subtitle: { en: "October 22, 2025", ar: "October 22, 2025" }, blocks: SET_BLOCKS[10] };
byKey["baba-13"] = { id: "katameros-baba-13", title: {"en":"13 Baba","ar":"13 بابه"}, subtitle: { en: "October 23, 2025", ar: "October 23, 2025" }, blocks: SET_BLOCKS[48] };
byKey["baba-14"] = { id: "katameros-baba-14", title: {"en":"14 Baba","ar":"14 بابه"}, subtitle: { en: "October 24, 2025", ar: "October 24, 2025" }, blocks: SET_BLOCKS[11] };
byKey["baba-15"] = { id: "katameros-baba-15", title: {"en":"15 Baba","ar":"15 بابه"}, subtitle: { en: "October 25, 2025", ar: "October 25, 2025" }, blocks: SET_BLOCKS[56] };
byKey["baba-16"] = { id: "katameros-baba-16", title: {"en":"16 Baba","ar":"16 بابه"}, subtitle: { en: "October 26, 2025", ar: "October 26, 2025" }, blocks: SET_BLOCKS[24] };
byKey["baba-17"] = { id: "katameros-baba-17", title: {"en":"17 Baba","ar":"17 بابه"}, subtitle: { en: "October 27, 2025", ar: "October 27, 2025" }, blocks: SET_BLOCKS[54] };
byKey["baba-18"] = { id: "katameros-baba-18", title: {"en":"18 Baba","ar":"18 بابه"}, subtitle: { en: "October 28, 2025", ar: "October 28, 2025" }, blocks: SET_BLOCKS[24] };
byKey["baba-19"] = { id: "katameros-baba-19", title: {"en":"19 Baba","ar":"19 بابه"}, subtitle: { en: "October 29, 2025", ar: "October 29, 2025" }, blocks: SET_BLOCKS[56] };
byKey["baba-20"] = { id: "katameros-baba-20", title: {"en":"20 Baba","ar":"20 بابه"}, subtitle: { en: "October 30, 2025", ar: "October 30, 2025" }, blocks: SET_BLOCKS[40] };
byKey["baba-21"] = { id: "katameros-baba-21", title: {"en":"21 Baba","ar":"21 بابه"}, subtitle: { en: "October 31, 2025", ar: "October 31, 2025" }, blocks: SET_BLOCKS[3] };
byKey["baba-22"] = { id: "katameros-baba-22", title: {"en":"22 Baba","ar":"22 بابه"}, subtitle: { en: "November 1, 2025", ar: "November 1, 2025" }, blocks: SET_BLOCKS[12] };
byKey["baba-23"] = { id: "katameros-baba-23", title: {"en":"23 Baba","ar":"23 بابه"}, subtitle: { en: "November 2, 2025", ar: "November 2, 2025" }, blocks: SET_BLOCKS[23] };
byKey["baba-24"] = { id: "katameros-baba-24", title: {"en":"24 Baba","ar":"24 بابه"}, subtitle: { en: "November 3, 2025", ar: "November 3, 2025" }, blocks: SET_BLOCKS[37] };
byKey["baba-25"] = { id: "katameros-baba-25", title: {"en":"25 Baba","ar":"25 بابه"}, subtitle: { en: "November 4, 2025", ar: "November 4, 2025" }, blocks: SET_BLOCKS[48] };
byKey["baba-26"] = { id: "katameros-baba-26", title: {"en":"26 Baba","ar":"26 بابه"}, subtitle: { en: "November 5, 2025", ar: "November 5, 2025" }, blocks: SET_BLOCKS[29] };
byKey["baba-27"] = { id: "katameros-baba-27", title: {"en":"27 Baba","ar":"27 بابه"}, subtitle: { en: "November 6, 2025", ar: "November 6, 2025" }, blocks: SET_BLOCKS[13] };
byKey["baba-28"] = { id: "katameros-baba-28", title: {"en":"28 Baba","ar":"28 بابه"}, subtitle: { en: "November 7, 2025", ar: "November 7, 2025" }, blocks: SET_BLOCKS[21] };
byKey["baba-29"] = { id: "katameros-baba-29", title: {"en":"29 Baba","ar":"29 بابه"}, subtitle: { en: "November 8, 2025", ar: "November 8, 2025" }, blocks: SET_BLOCKS[22] };
byKey["baba-30"] = { id: "katameros-baba-30", title: {"en":"30 Baba","ar":"30 بابه"}, subtitle: { en: "November 9, 2025", ar: "November 9, 2025" }, blocks: SET_BLOCKS[45] };
byKey["hator-1"] = { id: "katameros-hator-1", title: {"en":"1 Hator","ar":"1 هاتور"}, subtitle: { en: "November 10, 2025", ar: "November 10, 2025" }, blocks: SET_BLOCKS[54] };
byKey["hator-2"] = { id: "katameros-hator-2", title: {"en":"2 Hator","ar":"2 هاتور"}, subtitle: { en: "November 11, 2025", ar: "November 11, 2025" }, blocks: SET_BLOCKS[24] };
byKey["hator-3"] = { id: "katameros-hator-3", title: {"en":"3 Hator","ar":"3 هاتور"}, subtitle: { en: "November 12, 2025", ar: "November 12, 2025" }, blocks: SET_BLOCKS[15] };
byKey["hator-4"] = { id: "katameros-hator-4", title: {"en":"4 Hator","ar":"4 هاتور"}, subtitle: { en: "November 13, 2025", ar: "November 13, 2025" }, blocks: SET_BLOCKS[23] };
byKey["hator-5"] = { id: "katameros-hator-5", title: {"en":"5 Hator","ar":"5 هاتور"}, subtitle: { en: "November 14, 2025", ar: "November 14, 2025" }, blocks: SET_BLOCKS[22] };
byKey["hator-6"] = { id: "katameros-hator-6", title: {"en":"6 Hator","ar":"6 هاتور"}, subtitle: { en: "November 15, 2025", ar: "November 15, 2025" }, blocks: SET_BLOCKS[18] };
byKey["hator-7"] = { id: "katameros-hator-7", title: {"en":"7 Hator","ar":"7 هاتور"}, subtitle: { en: "November 16, 2025", ar: "November 16, 2025" }, blocks: SET_BLOCKS[43] };
byKey["hator-8"] = { id: "katameros-hator-8", title: {"en":"8 Hator","ar":"8 هاتور"}, subtitle: { en: "November 17, 2025", ar: "November 17, 2025" }, blocks: SET_BLOCKS[14] };
byKey["hator-9"] = { id: "katameros-hator-9", title: {"en":"9 Hator","ar":"9 هاتور"}, subtitle: { en: "November 18, 2025", ar: "November 18, 2025" }, blocks: SET_BLOCKS[15] };
byKey["hator-10"] = { id: "katameros-hator-10", title: {"en":"10 Hator","ar":"10 هاتور"}, subtitle: { en: "November 19, 2025", ar: "November 19, 2025" }, blocks: SET_BLOCKS[39] };
byKey["hator-11"] = { id: "katameros-hator-11", title: {"en":"11 Hator","ar":"11 هاتور"}, subtitle: { en: "November 20, 2025", ar: "November 20, 2025" }, blocks: SET_BLOCKS[9] };
byKey["hator-12"] = { id: "katameros-hator-12", title: {"en":"12 Hator","ar":"12 هاتور"}, subtitle: { en: "November 21, 2025", ar: "November 21, 2025" }, blocks: SET_BLOCKS[16] };
byKey["hator-13"] = { id: "katameros-hator-13", title: {"en":"13 Hator","ar":"13 هاتور"}, subtitle: { en: "November 22, 2025", ar: "November 22, 2025" }, blocks: SET_BLOCKS[54] };
byKey["hator-14"] = { id: "katameros-hator-14", title: {"en":"14 Hator","ar":"14 هاتور"}, subtitle: { en: "November 23, 2025", ar: "November 23, 2025" }, blocks: SET_BLOCKS[23] };
byKey["hator-15"] = { id: "katameros-hator-15", title: {"en":"15 Hator","ar":"15 هاتور"}, subtitle: { en: "November 24, 2025", ar: "November 24, 2025" }, blocks: SET_BLOCKS[17] };
byKey["hator-16"] = { id: "katameros-hator-16", title: {"en":"16 Hator","ar":"16 هاتور"}, subtitle: { en: "November 25, 2025", ar: "November 25, 2025" }, blocks: SET_BLOCKS[52] };
byKey["hator-17"] = { id: "katameros-hator-17", title: {"en":"17 Hator","ar":"17 هاتور"}, subtitle: { en: "November 26, 2025", ar: "November 26, 2025" }, blocks: SET_BLOCKS[18] };
byKey["hator-18"] = { id: "katameros-hator-18", title: {"en":"18 Hator","ar":"18 هاتور"}, subtitle: { en: "November 27, 2025", ar: "November 27, 2025" }, blocks: SET_BLOCKS[55] };
byKey["hator-19"] = { id: "katameros-hator-19", title: {"en":"19 Hator","ar":"19 هاتور"}, subtitle: { en: "November 28, 2025", ar: "November 28, 2025" }, blocks: SET_BLOCKS[41] };
byKey["hator-20"] = { id: "katameros-hator-20", title: {"en":"20 Hator","ar":"20 هاتور"}, subtitle: { en: "November 29, 2025", ar: "November 29, 2025" }, blocks: SET_BLOCKS[45] };
byKey["hator-21"] = { id: "katameros-hator-21", title: {"en":"21 Hator","ar":"21 هاتور"}, subtitle: { en: "November 30, 2025", ar: "November 30, 2025" }, blocks: SET_BLOCKS[18] };
byKey["hator-22"] = { id: "katameros-hator-22", title: {"en":"22 Hator","ar":"22 هاتور"}, subtitle: { en: "December 1, 2025", ar: "December 1, 2025" }, blocks: SET_BLOCKS[19] };
byKey["hator-23"] = { id: "katameros-hator-23", title: {"en":"23 Hator","ar":"23 هاتور"}, subtitle: { en: "December 2, 2025", ar: "December 2, 2025" }, blocks: SET_BLOCKS[23] };
byKey["hator-24"] = { id: "katameros-hator-24", title: {"en":"24 Hator","ar":"24 هاتور"}, subtitle: { en: "December 3, 2025", ar: "December 3, 2025" }, blocks: SET_BLOCKS[20] };
byKey["hator-25"] = { id: "katameros-hator-25", title: {"en":"25 Hator","ar":"25 هاتور"}, subtitle: { en: "December 4, 2025", ar: "December 4, 2025" }, blocks: SET_BLOCKS[21] };
byKey["hator-26"] = { id: "katameros-hator-26", title: {"en":"26 Hator","ar":"26 هاتور"}, subtitle: { en: "December 5, 2025", ar: "December 5, 2025" }, blocks: SET_BLOCKS[19] };
byKey["hator-27"] = { id: "katameros-hator-27", title: {"en":"27 Hator","ar":"27 هاتور"}, subtitle: { en: "December 6, 2025", ar: "December 6, 2025" }, blocks: SET_BLOCKS[22] };
byKey["hator-28"] = { id: "katameros-hator-28", title: {"en":"28 Hator","ar":"28 هاتور"}, subtitle: { en: "December 7, 2025", ar: "December 7, 2025" }, blocks: SET_BLOCKS[23] };
byKey["hator-29"] = { id: "katameros-hator-29", title: {"en":"29 Hator","ar":"29 هاتور"}, subtitle: { en: "December 8, 2025", ar: "December 8, 2025" }, blocks: SET_BLOCKS[24] };
byKey["hator-30"] = { id: "katameros-hator-30", title: {"en":"30 Hator","ar":"30 هاتور"}, subtitle: { en: "December 9, 2025", ar: "December 9, 2025" }, blocks: SET_BLOCKS[54] };
byKey["kiahk-1"] = { id: "katameros-kiahk-1", title: {"en":"1 Kiahk","ar":"1 كيهك"}, subtitle: { en: "December 10, 2025", ar: "December 10, 2025" }, blocks: SET_BLOCKS[18] };
byKey["kiahk-2"] = { id: "katameros-kiahk-2", title: {"en":"2 Kiahk","ar":"2 كيهك"}, subtitle: { en: "December 11, 2025", ar: "December 11, 2025" }, blocks: SET_BLOCKS[52] };
byKey["kiahk-3"] = { id: "katameros-kiahk-3", title: {"en":"3 Kiahk","ar":"3 كيهك"}, subtitle: { en: "December 12, 2025", ar: "December 12, 2025" }, blocks: SET_BLOCKS[46] };
byKey["kiahk-4"] = { id: "katameros-kiahk-4", title: {"en":"4 Kiahk","ar":"4 كيهك"}, subtitle: { en: "December 13, 2025", ar: "December 13, 2025" }, blocks: SET_BLOCKS[55] };
byKey["kiahk-5"] = { id: "katameros-kiahk-5", title: {"en":"5 Kiahk","ar":"5 كيهك"}, subtitle: { en: "December 14, 2025", ar: "December 14, 2025" }, blocks: SET_BLOCKS[3] };
byKey["kiahk-6"] = { id: "katameros-kiahk-6", title: {"en":"6 Kiahk","ar":"6 كيهك"}, subtitle: { en: "December 15, 2025", ar: "December 15, 2025" }, blocks: SET_BLOCKS[54] };
byKey["kiahk-7"] = { id: "katameros-kiahk-7", title: {"en":"7 Kiahk","ar":"7 كيهك"}, subtitle: { en: "December 16, 2025", ar: "December 16, 2025" }, blocks: SET_BLOCKS[40] };
byKey["kiahk-8"] = { id: "katameros-kiahk-8", title: {"en":"8 Kiahk","ar":"8 كيهك"}, subtitle: { en: "December 17, 2025", ar: "December 17, 2025" }, blocks: SET_BLOCKS[41] };
byKey["kiahk-9"] = { id: "katameros-kiahk-9", title: {"en":"9 Kiahk","ar":"9 كيهك"}, subtitle: { en: "December 18, 2025", ar: "December 18, 2025" }, blocks: SET_BLOCKS[37] };
byKey["kiahk-10"] = { id: "katameros-kiahk-10", title: {"en":"10 Kiahk","ar":"10 كيهك"}, subtitle: { en: "December 19, 2025", ar: "December 19, 2025" }, blocks: SET_BLOCKS[23] };
byKey["kiahk-11"] = { id: "katameros-kiahk-11", title: {"en":"11 Kiahk","ar":"11 كيهك"}, subtitle: { en: "December 20, 2025", ar: "December 20, 2025" }, blocks: SET_BLOCKS[52] };
byKey["kiahk-12"] = { id: "katameros-kiahk-12", title: {"en":"12 Kiahk","ar":"12 كيهك"}, subtitle: { en: "December 21, 2025", ar: "December 21, 2025" }, blocks: SET_BLOCKS[48] };
byKey["kiahk-13"] = { id: "katameros-kiahk-13", title: {"en":"13 Kiahk","ar":"13 كيهك"}, subtitle: { en: "December 22, 2025", ar: "December 22, 2025" }, blocks: SET_BLOCKS[9] };
byKey["kiahk-14"] = { id: "katameros-kiahk-14", title: {"en":"14 Kiahk","ar":"14 كيهك"}, subtitle: { en: "December 23, 2025", ar: "December 23, 2025" }, blocks: SET_BLOCKS[44] };
byKey["kiahk-15"] = { id: "katameros-kiahk-15", title: {"en":"15 Kiahk","ar":"15 كيهك"}, subtitle: { en: "December 24, 2025", ar: "December 24, 2025" }, blocks: SET_BLOCKS[18] };
byKey["kiahk-16"] = { id: "katameros-kiahk-16", title: {"en":"16 Kiahk","ar":"16 كيهك"}, subtitle: { en: "December 25, 2025", ar: "December 25, 2025" }, blocks: SET_BLOCKS[22] };
byKey["kiahk-17"] = { id: "katameros-kiahk-17", title: {"en":"17 Kiahk","ar":"17 كيهك"}, subtitle: { en: "December 26, 2025", ar: "December 26, 2025" }, blocks: SET_BLOCKS[57] };
byKey["kiahk-18"] = { id: "katameros-kiahk-18", title: {"en":"18 Kiahk","ar":"18 كيهك"}, subtitle: { en: "December 27, 2025", ar: "December 27, 2025" }, blocks: SET_BLOCKS[12] };
byKey["kiahk-19"] = { id: "katameros-kiahk-19", title: {"en":"19 Kiahk","ar":"19 كيهك"}, subtitle: { en: "December 28, 2025", ar: "December 28, 2025" }, blocks: SET_BLOCKS[23] };
byKey["kiahk-20"] = { id: "katameros-kiahk-20", title: {"en":"20 Kiahk","ar":"20 كيهك"}, subtitle: { en: "December 29, 2025", ar: "December 29, 2025" }, blocks: SET_BLOCKS[3] };
byKey["kiahk-21"] = { id: "katameros-kiahk-21", title: {"en":"21 Kiahk","ar":"21 كيهك"}, subtitle: { en: "December 30, 2025", ar: "December 30, 2025" }, blocks: SET_BLOCKS[55] };
byKey["kiahk-22"] = { id: "katameros-kiahk-22", title: {"en":"22 Kiahk","ar":"22 كيهك"}, subtitle: { en: "December 31, 2025", ar: "December 31, 2025" }, blocks: SET_BLOCKS[25] };
byKey["kiahk-23"] = { id: "katameros-kiahk-23", title: {"en":"23 Kiahk","ar":"23 كيهك"}, subtitle: { en: "January 1, 2026", ar: "January 1, 2026" }, blocks: SET_BLOCKS[70] };
byKey["kiahk-24"] = { id: "katameros-kiahk-24", title: {"en":"24 Kiahk","ar":"24 كيهك"}, subtitle: { en: "January 2, 2026", ar: "January 2, 2026" }, blocks: SET_BLOCKS[31] };
byKey["kiahk-25"] = { id: "katameros-kiahk-25", title: {"en":"25 Kiahk","ar":"25 كيهك"}, subtitle: { en: "January 3, 2026", ar: "January 3, 2026" }, blocks: SET_BLOCKS[40] };
byKey["kiahk-26"] = { id: "katameros-kiahk-26", title: {"en":"26 Kiahk","ar":"26 كيهك"}, subtitle: { en: "January 4, 2026", ar: "January 4, 2026" }, blocks: SET_BLOCKS[39] };
byKey["kiahk-27"] = { id: "katameros-kiahk-27", title: {"en":"27 Kiahk","ar":"27 كيهك"}, subtitle: { en: "January 5, 2026", ar: "January 5, 2026" }, blocks: SET_BLOCKS[23] };
byKey["kiahk-28"] = { id: "katameros-kiahk-28", title: {"en":"28 Kiahk","ar":"28 كيهك"}, subtitle: { en: "January 6, 2026", ar: "January 6, 2026" }, blocks: SET_BLOCKS[26] };
byKey["kiahk-29"] = { id: "katameros-kiahk-29", title: {"en":"29 Kiahk","ar":"29 كيهك"}, subtitle: { en: "January 7, 2026", ar: "January 7, 2026" }, blocks: SET_BLOCKS[27] };
byKey["kiahk-30"] = { id: "katameros-kiahk-30", title: {"en":"30 Kiahk","ar":"30 كيهك"}, subtitle: { en: "January 8, 2026", ar: "January 8, 2026" }, blocks: SET_BLOCKS[28] };
byKey["toba-1"] = { id: "katameros-toba-1", title: {"en":"1 Toba","ar":"1 طوبة"}, subtitle: { en: "January 9, 2026", ar: "January 9, 2026" }, blocks: SET_BLOCKS[29] };
byKey["toba-2"] = { id: "katameros-toba-2", title: {"en":"2 Toba","ar":"2 طوبة"}, subtitle: { en: "January 10, 2026", ar: "January 10, 2026" }, blocks: SET_BLOCKS[54] };
byKey["toba-3"] = { id: "katameros-toba-3", title: {"en":"3 Toba","ar":"3 طوبة"}, subtitle: { en: "January 11, 2026", ar: "January 11, 2026" }, blocks: SET_BLOCKS[30] };
byKey["toba-4"] = { id: "katameros-toba-4", title: {"en":"4 Toba","ar":"4 طوبة"}, subtitle: { en: "January 12, 2026", ar: "January 12, 2026" }, blocks: SET_BLOCKS[31] };
byKey["toba-5"] = { id: "katameros-toba-5", title: {"en":"5 Toba","ar":"5 طوبة"}, subtitle: { en: "January 13, 2026", ar: "January 13, 2026" }, blocks: SET_BLOCKS[21] };
byKey["toba-6"] = { id: "katameros-toba-6", title: {"en":"6 Toba","ar":"6 طوبة"}, subtitle: { en: "January 14, 2026", ar: "January 14, 2026" }, blocks: SET_BLOCKS[32] };
byKey["toba-7"] = { id: "katameros-toba-7", title: {"en":"7 Toba","ar":"7 طوبة"}, subtitle: { en: "January 15, 2026", ar: "January 15, 2026" }, blocks: SET_BLOCKS[18] };
byKey["toba-8"] = { id: "katameros-toba-8", title: {"en":"8 Toba","ar":"8 طوبة"}, subtitle: { en: "January 16, 2026", ar: "January 16, 2026" }, blocks: SET_BLOCKS[54] };
byKey["toba-9"] = { id: "katameros-toba-9", title: {"en":"9 Toba","ar":"9 طوبة"}, subtitle: { en: "January 17, 2026", ar: "January 17, 2026" }, blocks: SET_BLOCKS[13] };
byKey["toba-10"] = { id: "katameros-toba-10", title: {"en":"10 Toba","ar":"10 طوبة"}, subtitle: { en: "January 18, 2026", ar: "January 18, 2026" }, blocks: SET_BLOCKS[33] };
byKey["toba-11"] = { id: "katameros-toba-11", title: {"en":"11 Toba","ar":"11 طوبة"}, subtitle: { en: "January 19, 2026", ar: "January 19, 2026" }, blocks: SET_BLOCKS[34] };
byKey["toba-12"] = { id: "katameros-toba-12", title: {"en":"12 Toba","ar":"12 طوبة"}, subtitle: { en: "January 20, 2026", ar: "January 20, 2026" }, blocks: SET_BLOCKS[35] };
byKey["toba-13"] = { id: "katameros-toba-13", title: {"en":"13 Toba","ar":"13 طوبة"}, subtitle: { en: "January 21, 2026", ar: "January 21, 2026" }, blocks: SET_BLOCKS[36] };
byKey["toba-14"] = { id: "katameros-toba-14", title: {"en":"14 Toba","ar":"14 طوبة"}, subtitle: { en: "January 22, 2026", ar: "January 22, 2026" }, blocks: SET_BLOCKS[48] };
byKey["toba-15"] = { id: "katameros-toba-15", title: {"en":"15 Toba","ar":"15 طوبة"}, subtitle: { en: "January 23, 2026", ar: "January 23, 2026" }, blocks: SET_BLOCKS[3] };
byKey["toba-16"] = { id: "katameros-toba-16", title: {"en":"16 Toba","ar":"16 طوبة"}, subtitle: { en: "January 24, 2026", ar: "January 24, 2026" }, blocks: SET_BLOCKS[44] };
byKey["toba-17"] = { id: "katameros-toba-17", title: {"en":"17 Toba","ar":"17 طوبة"}, subtitle: { en: "January 25, 2026", ar: "January 25, 2026" }, blocks: SET_BLOCKS[52] };
byKey["toba-18"] = { id: "katameros-toba-18", title: {"en":"18 Toba","ar":"18 طوبة"}, subtitle: { en: "January 26, 2026", ar: "January 26, 2026" }, blocks: SET_BLOCKS[23] };
byKey["toba-19"] = { id: "katameros-toba-19", title: {"en":"19 Toba","ar":"19 طوبة"}, subtitle: { en: "January 27, 2026", ar: "January 27, 2026" }, blocks: SET_BLOCKS[19] };
byKey["toba-20"] = { id: "katameros-toba-20", title: {"en":"20 Toba","ar":"20 طوبة"}, subtitle: { en: "January 28, 2026", ar: "January 28, 2026" }, blocks: SET_BLOCKS[29] };
byKey["toba-21"] = { id: "katameros-toba-21", title: {"en":"21 Toba","ar":"21 طوبة"}, subtitle: { en: "January 29, 2026", ar: "January 29, 2026" }, blocks: SET_BLOCKS[46] };
byKey["toba-22"] = { id: "katameros-toba-22", title: {"en":"22 Toba","ar":"22 طوبة"}, subtitle: { en: "January 30, 2026", ar: "January 30, 2026" }, blocks: SET_BLOCKS[37] };
byKey["toba-23"] = { id: "katameros-toba-23", title: {"en":"23 Toba","ar":"23 طوبة"}, subtitle: { en: "January 31, 2026", ar: "January 31, 2026" }, blocks: SET_BLOCKS[23] };
byKey["toba-24"] = { id: "katameros-toba-24", title: {"en":"24 Toba","ar":"24 طوبة"}, subtitle: { en: "February 1, 2026", ar: "February 1, 2026" }, blocks: SET_BLOCKS[39] };
byKey["toba-25"] = { id: "katameros-toba-25", title: {"en":"25 Toba","ar":"25 طوبة"}, subtitle: { en: "February 2, 2026", ar: "February 2, 2026" }, blocks: SET_BLOCKS[48] };
byKey["toba-26"] = { id: "katameros-toba-26", title: {"en":"26 Toba","ar":"26 طوبة"}, subtitle: { en: "February 3, 2026", ar: "February 3, 2026" }, blocks: SET_BLOCKS[38] };
byKey["toba-27"] = { id: "katameros-toba-27", title: {"en":"27 Toba","ar":"27 طوبة"}, subtitle: { en: "February 4, 2026", ar: "February 4, 2026" }, blocks: SET_BLOCKS[44] };
byKey["toba-28"] = { id: "katameros-toba-28", title: {"en":"28 Toba","ar":"28 طوبة"}, subtitle: { en: "February 5, 2026", ar: "February 5, 2026" }, blocks: SET_BLOCKS[17] };
byKey["toba-29"] = { id: "katameros-toba-29", title: {"en":"29 Toba","ar":"29 طوبة"}, subtitle: { en: "February 6, 2026", ar: "February 6, 2026" }, blocks: SET_BLOCKS[46] };
byKey["toba-30"] = { id: "katameros-toba-30", title: {"en":"30 Toba","ar":"30 طوبة"}, subtitle: { en: "February 7, 2026", ar: "February 7, 2026" }, blocks: SET_BLOCKS[39] };
byKey["amshir-1"] = { id: "katameros-amshir-1", title: {"en":"1 Amshir","ar":"1 أمشير"}, subtitle: { en: "February 8, 2026", ar: "February 8, 2026" }, blocks: SET_BLOCKS[5] };
byKey["amshir-2"] = { id: "katameros-amshir-2", title: {"en":"2 Amshir","ar":"2 أمشير"}, subtitle: { en: "February 9, 2026", ar: "February 9, 2026" }, blocks: SET_BLOCKS[0] };
byKey["amshir-3"] = { id: "katameros-amshir-3", title: {"en":"3 Amshir","ar":"3 أمشير"}, subtitle: { en: "February 10, 2026", ar: "February 10, 2026" }, blocks: SET_BLOCKS[8] };
byKey["amshir-4"] = { id: "katameros-amshir-4", title: {"en":"4 Amshir","ar":"4 أمشير"}, subtitle: { en: "February 11, 2026", ar: "February 11, 2026" }, blocks: SET_BLOCKS[2] };
byKey["amshir-5"] = { id: "katameros-amshir-5", title: {"en":"5 Amshir","ar":"5 أمشير"}, subtitle: { en: "February 12, 2026", ar: "February 12, 2026" }, blocks: SET_BLOCKS[3] };
byKey["amshir-6"] = { id: "katameros-amshir-6", title: {"en":"6 Amshir","ar":"6 أمشير"}, subtitle: { en: "February 13, 2026", ar: "February 13, 2026" }, blocks: SET_BLOCKS[7] };
byKey["amshir-7"] = { id: "katameros-amshir-7", title: {"en":"7 Amshir","ar":"7 أمشير"}, subtitle: { en: "February 14, 2026", ar: "February 14, 2026" }, blocks: SET_BLOCKS[4] };
byKey["amshir-8"] = { id: "katameros-amshir-8", title: {"en":"8 Amshir","ar":"8 أمشير"}, subtitle: { en: "February 15, 2026", ar: "February 15, 2026" }, blocks: SET_BLOCKS[2] };
byKey["amshir-9"] = { id: "katameros-amshir-9", title: {"en":"9 Amshir","ar":"9 أمشير"}, subtitle: { en: "February 16, 2026", ar: "February 16, 2026" }, blocks: SET_BLOCKS[7] };
byKey["amshir-10"] = { id: "katameros-amshir-10", title: {"en":"10 Amshir","ar":"10 أمشير"}, subtitle: { en: "February 17, 2026", ar: "February 17, 2026" }, blocks: SET_BLOCKS[55] };
byKey["amshir-11"] = { id: "katameros-amshir-11", title: {"en":"11 Amshir","ar":"11 أمشير"}, subtitle: { en: "February 18, 2026", ar: "February 18, 2026" }, blocks: SET_BLOCKS[24] };
byKey["amshir-12"] = { id: "katameros-amshir-12", title: {"en":"12 Amshir","ar":"12 أمشير"}, subtitle: { en: "February 19, 2026", ar: "February 19, 2026" }, blocks: SET_BLOCKS[48] };
byKey["amshir-13"] = { id: "katameros-amshir-13", title: {"en":"13 Amshir","ar":"13 أمشير"}, subtitle: { en: "February 20, 2026", ar: "February 20, 2026" }, blocks: SET_BLOCKS[44] };
byKey["amshir-14"] = { id: "katameros-amshir-14", title: {"en":"14 Amshir","ar":"14 أمشير"}, subtitle: { en: "February 21, 2026", ar: "February 21, 2026" }, blocks: SET_BLOCKS[18] };
byKey["amshir-15"] = { id: "katameros-amshir-15", title: {"en":"15 Amshir","ar":"15 أمشير"}, subtitle: { en: "February 22, 2026", ar: "February 22, 2026" }, blocks: SET_BLOCKS[52] };
byKey["amshir-16"] = { id: "katameros-amshir-16", title: {"en":"16 Amshir","ar":"16 أمشير"}, subtitle: { en: "February 23, 2026", ar: "February 23, 2026" }, blocks: SET_BLOCKS[4] };
byKey["amshir-17"] = { id: "katameros-amshir-17", title: {"en":"17 Amshir","ar":"17 أمشير"}, subtitle: { en: "February 24, 2026", ar: "February 24, 2026" }, blocks: SET_BLOCKS[44] };
byKey["amshir-18"] = { id: "katameros-amshir-18", title: {"en":"18 Amshir","ar":"18 أمشير"}, subtitle: { en: "February 25, 2026", ar: "February 25, 2026" }, blocks: SET_BLOCKS[18] };
byKey["amshir-19"] = { id: "katameros-amshir-19", title: {"en":"19 Amshir","ar":"19 أمشير"}, subtitle: { en: "February 26, 2026", ar: "February 26, 2026" }, blocks: SET_BLOCKS[48] };
byKey["amshir-20"] = { id: "katameros-amshir-20", title: {"en":"20 Amshir","ar":"20 أمشير"}, subtitle: { en: "February 27, 2026", ar: "February 27, 2026" }, blocks: SET_BLOCKS[24] };
byKey["amshir-21"] = { id: "katameros-amshir-21", title: {"en":"21 Amshir","ar":"21 أمشير"}, subtitle: { en: "February 28, 2026", ar: "February 28, 2026" }, blocks: SET_BLOCKS[55] };
byKey["amshir-22"] = { id: "katameros-amshir-22", title: {"en":"22 Amshir","ar":"22 أمشير"}, subtitle: { en: "March 1, 2026", ar: "March 1, 2026" }, blocks: SET_BLOCKS[23] };
byKey["amshir-23"] = { id: "katameros-amshir-23", title: {"en":"23 Amshir","ar":"23 أمشير"}, subtitle: { en: "March 2, 2026", ar: "March 2, 2026" }, blocks: SET_BLOCKS[44] };
byKey["amshir-24"] = { id: "katameros-amshir-24", title: {"en":"24 Amshir","ar":"24 أمشير"}, subtitle: { en: "March 3, 2026", ar: "March 3, 2026" }, blocks: SET_BLOCKS[45] };
byKey["amshir-25"] = { id: "katameros-amshir-25", title: {"en":"25 Amshir","ar":"25 أمشير"}, subtitle: { en: "March 4, 2026", ar: "March 4, 2026" }, blocks: SET_BLOCKS[56] };
byKey["amshir-26"] = { id: "katameros-amshir-26", title: {"en":"26 Amshir","ar":"26 أمشير"}, subtitle: { en: "March 5, 2026", ar: "March 5, 2026" }, blocks: SET_BLOCKS[3] };
byKey["amshir-27"] = { id: "katameros-amshir-27", title: {"en":"27 Amshir","ar":"27 أمشير"}, subtitle: { en: "March 6, 2026", ar: "March 6, 2026" }, blocks: SET_BLOCKS[18] };
byKey["amshir-28"] = { id: "katameros-amshir-28", title: {"en":"28 Amshir","ar":"28 أمشير"}, subtitle: { en: "March 7, 2026", ar: "March 7, 2026" }, blocks: SET_BLOCKS[56] };
byKey["amshir-29"] = { id: "katameros-amshir-29", title: {"en":"29 Amshir","ar":"29 أمشير"}, subtitle: { en: "March 8, 2026", ar: "March 8, 2026" }, blocks: SET_BLOCKS[30] };
byKey["amshir-30"] = { id: "katameros-amshir-30", title: {"en":"30 Amshir","ar":"30 أمشير"}, subtitle: { en: "March 9, 2026", ar: "March 9, 2026" }, blocks: SET_BLOCKS[51] };
byKey["baramhat-1"] = { id: "katameros-baramhat-1", title: {"en":"1 Baramhat","ar":"1 برمهات"}, subtitle: { en: "March 10, 2026", ar: "March 10, 2026" }, blocks: SET_BLOCKS[19] };
byKey["baramhat-2"] = { id: "katameros-baramhat-2", title: {"en":"2 Baramhat","ar":"2 برمهات"}, subtitle: { en: "March 11, 2026", ar: "March 11, 2026" }, blocks: SET_BLOCKS[23] };
byKey["baramhat-3"] = { id: "katameros-baramhat-3", title: {"en":"3 Baramhat","ar":"3 برمهات"}, subtitle: { en: "March 12, 2026", ar: "March 12, 2026" }, blocks: SET_BLOCKS[24] };
byKey["baramhat-4"] = { id: "katameros-baramhat-4", title: {"en":"4 Baramhat","ar":"4 برمهات"}, subtitle: { en: "March 13, 2026", ar: "March 13, 2026" }, blocks: SET_BLOCKS[15] };
byKey["baramhat-5"] = { id: "katameros-baramhat-5", title: {"en":"5 Baramhat","ar":"5 برمهات"}, subtitle: { en: "March 14, 2026", ar: "March 14, 2026" }, blocks: SET_BLOCKS[23] };
byKey["baramhat-6"] = { id: "katameros-baramhat-6", title: {"en":"6 Baramhat","ar":"6 برمهات"}, subtitle: { en: "March 15, 2026", ar: "March 15, 2026" }, blocks: SET_BLOCKS[22] };
byKey["baramhat-7"] = { id: "katameros-baramhat-7", title: {"en":"7 Baramhat","ar":"7 برمهات"}, subtitle: { en: "March 16, 2026", ar: "March 16, 2026" }, blocks: SET_BLOCKS[19] };
byKey["baramhat-8"] = { id: "katameros-baramhat-8", title: {"en":"8 Baramhat","ar":"8 برمهات"}, subtitle: { en: "March 17, 2026", ar: "March 17, 2026" }, blocks: SET_BLOCKS[55] };
byKey["baramhat-9"] = { id: "katameros-baramhat-9", title: {"en":"9 Baramhat","ar":"9 برمهات"}, subtitle: { en: "March 18, 2026", ar: "March 18, 2026" }, blocks: SET_BLOCKS[48] };
byKey["baramhat-10"] = { id: "katameros-baramhat-10", title: {"en":"10 Baramhat","ar":"10 برمهات"}, subtitle: { en: "March 19, 2026", ar: "March 19, 2026" }, blocks: SET_BLOCKS[5] };
byKey["baramhat-11"] = { id: "katameros-baramhat-11", title: {"en":"11 Baramhat","ar":"11 برمهات"}, subtitle: { en: "March 20, 2026", ar: "March 20, 2026" }, blocks: SET_BLOCKS[8] };
byKey["baramhat-12"] = { id: "katameros-baramhat-12", title: {"en":"12 Baramhat","ar":"12 برمهات"}, subtitle: { en: "March 21, 2026", ar: "March 21, 2026" }, blocks: SET_BLOCKS[24] };
byKey["baramhat-13"] = { id: "katameros-baramhat-13", title: {"en":"13 Baramhat","ar":"13 برمهات"}, subtitle: { en: "March 22, 2026", ar: "March 22, 2026" }, blocks: SET_BLOCKS[41] };
byKey["baramhat-14"] = { id: "katameros-baramhat-14", title: {"en":"14 Baramhat","ar":"14 برمهات"}, subtitle: { en: "March 23, 2026", ar: "March 23, 2026" }, blocks: SET_BLOCKS[8] };
byKey["baramhat-15"] = { id: "katameros-baramhat-15", title: {"en":"15 Baramhat","ar":"15 برمهات"}, subtitle: { en: "March 24, 2026", ar: "March 24, 2026" }, blocks: SET_BLOCKS[39] };
byKey["baramhat-16"] = { id: "katameros-baramhat-16", title: {"en":"16 Baramhat","ar":"16 برمهات"}, subtitle: { en: "March 25, 2026", ar: "March 25, 2026" }, blocks: SET_BLOCKS[24] };
byKey["baramhat-17"] = { id: "katameros-baramhat-17", title: {"en":"17 Baramhat","ar":"17 برمهات"}, subtitle: { en: "March 26, 2026", ar: "March 26, 2026" }, blocks: SET_BLOCKS[23] };
byKey["baramhat-18"] = { id: "katameros-baramhat-18", title: {"en":"18 Baramhat","ar":"18 برمهات"}, subtitle: { en: "March 27, 2026", ar: "March 27, 2026" }, blocks: SET_BLOCKS[56] };
byKey["baramhat-19"] = { id: "katameros-baramhat-19", title: {"en":"19 Baramhat","ar":"19 برمهات"}, subtitle: { en: "March 28, 2026", ar: "March 28, 2026" }, blocks: SET_BLOCKS[29] };
byKey["baramhat-20"] = { id: "katameros-baramhat-20", title: {"en":"20 Baramhat","ar":"20 برمهات"}, subtitle: { en: "March 29, 2026", ar: "March 29, 2026" }, blocks: SET_BLOCKS[24] };
byKey["baramhat-21"] = { id: "katameros-baramhat-21", title: {"en":"21 Baramhat","ar":"21 برمهات"}, subtitle: { en: "March 30, 2026", ar: "March 30, 2026" }, blocks: SET_BLOCKS[58] };
byKey["baramhat-22"] = { id: "katameros-baramhat-22", title: {"en":"22 Baramhat","ar":"22 برمهات"}, subtitle: { en: "March 31, 2026", ar: "March 31, 2026" }, blocks: SET_BLOCKS[54] };
byKey["baramhat-23"] = { id: "katameros-baramhat-23", title: {"en":"23 Baramhat","ar":"23 برمهات"}, subtitle: { en: "April 1, 2026", ar: "April 1, 2026" }, blocks: SET_BLOCKS[3] };
byKey["baramhat-24"] = { id: "katameros-baramhat-24", title: {"en":"24 Baramhat","ar":"24 برمهات"}, subtitle: { en: "April 2, 2026", ar: "April 2, 2026" }, blocks: SET_BLOCKS[24] };
byKey["baramhat-25"] = { id: "katameros-baramhat-25", title: {"en":"25 Baramhat","ar":"25 برمهات"}, subtitle: { en: "April 3, 2026", ar: "April 3, 2026" }, blocks: SET_BLOCKS[11] };
byKey["baramhat-26"] = { id: "katameros-baramhat-26", title: {"en":"26 Baramhat","ar":"26 برمهات"}, subtitle: { en: "April 4, 2026", ar: "April 4, 2026" }, blocks: SET_BLOCKS[39] };
byKey["baramhat-27"] = { id: "katameros-baramhat-27", title: {"en":"27 Baramhat","ar":"27 برمهات"}, subtitle: { en: "April 5, 2026", ar: "April 5, 2026" }, blocks: SET_BLOCKS[13] };
byKey["baramhat-28"] = { id: "katameros-baramhat-28", title: {"en":"28 Baramhat","ar":"28 برمهات"}, subtitle: { en: "April 6, 2026", ar: "April 6, 2026" }, blocks: SET_BLOCKS[4] };
byKey["baramhat-29"] = { id: "katameros-baramhat-29", title: {"en":"29 Baramhat","ar":"29 برمهات"}, subtitle: { en: "April 7, 2026", ar: "April 7, 2026" }, blocks: SET_BLOCKS[42] };
byKey["baramhat-30"] = { id: "katameros-baramhat-30", title: {"en":"30 Baramhat","ar":"30 برمهات"}, subtitle: { en: "April 8, 2026", ar: "April 8, 2026" }, blocks: SET_BLOCKS[25] };
byKey["baramouda-1"] = { id: "katameros-baramouda-1", title: {"en":"1 Baramouda","ar":"1 برمودة"}, subtitle: { en: "April 9, 2026", ar: "April 9, 2026" }, blocks: SET_BLOCKS[48] };
byKey["baramouda-2"] = { id: "katameros-baramouda-2", title: {"en":"2 Baramouda","ar":"2 برمودة"}, subtitle: { en: "April 10, 2026", ar: "April 10, 2026" }, blocks: SET_BLOCKS[56] };
byKey["baramouda-3"] = { id: "katameros-baramouda-3", title: {"en":"3 Baramouda","ar":"3 برمودة"}, subtitle: { en: "April 11, 2026", ar: "April 11, 2026" }, blocks: SET_BLOCKS[54] };
byKey["baramouda-4"] = { id: "katameros-baramouda-4", title: {"en":"4 Baramouda","ar":"4 برمودة"}, subtitle: { en: "April 12, 2026", ar: "April 12, 2026" }, blocks: SET_BLOCKS[19] };
byKey["baramouda-5"] = { id: "katameros-baramouda-5", title: {"en":"5 Baramouda","ar":"5 برمودة"}, subtitle: { en: "April 13, 2026", ar: "April 13, 2026" }, blocks: SET_BLOCKS[3] };
byKey["baramouda-6"] = { id: "katameros-baramouda-6", title: {"en":"6 Baramouda","ar":"6 برمودة"}, subtitle: { en: "April 14, 2026", ar: "April 14, 2026" }, blocks: SET_BLOCKS[39] };
byKey["baramouda-7"] = { id: "katameros-baramouda-7", title: {"en":"7 Baramouda","ar":"7 برمودة"}, subtitle: { en: "April 15, 2026", ar: "April 15, 2026" }, blocks: SET_BLOCKS[3] };
byKey["baramouda-8"] = { id: "katameros-baramouda-8", title: {"en":"8 Baramouda","ar":"8 برمودة"}, subtitle: { en: "April 16, 2026", ar: "April 16, 2026" }, blocks: SET_BLOCKS[39] };
byKey["baramouda-9"] = { id: "katameros-baramouda-9", title: {"en":"9 Baramouda","ar":"9 برمودة"}, subtitle: { en: "April 17, 2026", ar: "April 17, 2026" }, blocks: SET_BLOCKS[37] };
byKey["baramouda-10"] = { id: "katameros-baramouda-10", title: {"en":"10 Baramouda","ar":"10 برمودة"}, subtitle: { en: "April 18, 2026", ar: "April 18, 2026" }, blocks: SET_BLOCKS[48] };
byKey["baramouda-11"] = { id: "katameros-baramouda-11", title: {"en":"11 Baramouda","ar":"11 برمودة"}, subtitle: { en: "April 19, 2026", ar: "April 19, 2026" }, blocks: SET_BLOCKS[39] };
byKey["baramouda-12"] = { id: "katameros-baramouda-12", title: {"en":"12 Baramouda","ar":"12 برمودة"}, subtitle: { en: "April 20, 2026", ar: "April 20, 2026" }, blocks: SET_BLOCKS[54] };
byKey["baramouda-13"] = { id: "katameros-baramouda-13", title: {"en":"13 Baramouda","ar":"13 برمودة"}, subtitle: { en: "April 21, 2026", ar: "April 21, 2026" }, blocks: SET_BLOCKS[19] };
byKey["baramouda-14"] = { id: "katameros-baramouda-14", title: {"en":"14 Baramouda","ar":"14 برمودة"}, subtitle: { en: "April 22, 2026", ar: "April 22, 2026" }, blocks: SET_BLOCKS[24] };
byKey["baramouda-15"] = { id: "katameros-baramouda-15", title: {"en":"15 Baramouda","ar":"15 برمودة"}, subtitle: { en: "April 23, 2026", ar: "April 23, 2026" }, blocks: SET_BLOCKS[29] };
byKey["baramouda-16"] = { id: "katameros-baramouda-16", title: {"en":"16 Baramouda","ar":"16 برمودة"}, subtitle: { en: "April 24, 2026", ar: "April 24, 2026" }, blocks: SET_BLOCKS[31] };
byKey["baramouda-17"] = { id: "katameros-baramouda-17", title: {"en":"17 Baramouda","ar":"17 برمودة"}, subtitle: { en: "April 25, 2026", ar: "April 25, 2026" }, blocks: SET_BLOCKS[55] };
byKey["baramouda-18"] = { id: "katameros-baramouda-18", title: {"en":"18 Baramouda","ar":"18 برمودة"}, subtitle: { en: "April 26, 2026", ar: "April 26, 2026" }, blocks: SET_BLOCKS[44] };
byKey["baramouda-19"] = { id: "katameros-baramouda-19", title: {"en":"19 Baramouda","ar":"19 برمودة"}, subtitle: { en: "April 27, 2026", ar: "April 27, 2026" }, blocks: SET_BLOCKS[23] };
byKey["baramouda-20"] = { id: "katameros-baramouda-20", title: {"en":"20 Baramouda","ar":"20 برمودة"}, subtitle: { en: "April 28, 2026", ar: "April 28, 2026" }, blocks: SET_BLOCKS[56] };
byKey["baramouda-21"] = { id: "katameros-baramouda-21", title: {"en":"21 Baramouda","ar":"21 برمودة"}, subtitle: { en: "April 29, 2026", ar: "April 29, 2026" }, blocks: SET_BLOCKS[8] };
byKey["baramouda-22"] = { id: "katameros-baramouda-22", title: {"en":"22 Baramouda","ar":"22 برمودة"}, subtitle: { en: "April 30, 2026", ar: "April 30, 2026" }, blocks: SET_BLOCKS[24] };
byKey["baramouda-23"] = { id: "katameros-baramouda-23", title: {"en":"23 Baramouda","ar":"23 برمودة"}, subtitle: { en: "May 1, 2026", ar: "May 1, 2026" }, blocks: SET_BLOCKS[43] };
byKey["baramouda-24"] = { id: "katameros-baramouda-24", title: {"en":"24 Baramouda","ar":"24 برمودة"}, subtitle: { en: "May 2, 2026", ar: "May 2, 2026" }, blocks: SET_BLOCKS[56] };
byKey["baramouda-25"] = { id: "katameros-baramouda-25", title: {"en":"25 Baramouda","ar":"25 برمودة"}, subtitle: { en: "May 3, 2026", ar: "May 3, 2026" }, blocks: SET_BLOCKS[39] };
byKey["baramouda-26"] = { id: "katameros-baramouda-26", title: {"en":"26 Baramouda","ar":"26 برمودة"}, subtitle: { en: "May 4, 2026", ar: "May 4, 2026" }, blocks: SET_BLOCKS[56] };
byKey["baramouda-27"] = { id: "katameros-baramouda-27", title: {"en":"27 Baramouda","ar":"27 برمودة"}, subtitle: { en: "May 5, 2026", ar: "May 5, 2026" }, blocks: SET_BLOCKS[44] };
byKey["baramouda-28"] = { id: "katameros-baramouda-28", title: {"en":"28 Baramouda","ar":"28 برمودة"}, subtitle: { en: "May 6, 2026", ar: "May 6, 2026" }, blocks: SET_BLOCKS[21] };
byKey["baramouda-29"] = { id: "katameros-baramouda-29", title: {"en":"29 Baramouda","ar":"29 برمودة"}, subtitle: { en: "May 7, 2026", ar: "May 7, 2026" }, blocks: SET_BLOCKS[29] };
byKey["baramouda-30"] = { id: "katameros-baramouda-30", title: {"en":"30 Baramouda","ar":"30 برمودة"}, subtitle: { en: "May 8, 2026", ar: "May 8, 2026" }, blocks: SET_BLOCKS[45] };
byKey["bashans-1"] = { id: "katameros-bashans-1", title: {"en":"1 Bashans","ar":"1 بشنس"}, subtitle: { en: "May 9, 2026", ar: "May 9, 2026" }, blocks: SET_BLOCKS[46] };
byKey["bashans-2"] = { id: "katameros-bashans-2", title: {"en":"2 Bashans","ar":"2 بشنس"}, subtitle: { en: "May 10, 2026", ar: "May 10, 2026" }, blocks: SET_BLOCKS[57] };
byKey["bashans-3"] = { id: "katameros-bashans-3", title: {"en":"3 Bashans","ar":"3 بشنس"}, subtitle: { en: "May 11, 2026", ar: "May 11, 2026" }, blocks: SET_BLOCKS[29] };
byKey["bashans-4"] = { id: "katameros-bashans-4", title: {"en":"4 Bashans","ar":"4 بشنس"}, subtitle: { en: "May 12, 2026", ar: "May 12, 2026" }, blocks: SET_BLOCKS[24] };
byKey["bashans-5"] = { id: "katameros-bashans-5", title: {"en":"5 Bashans","ar":"5 بشنس"}, subtitle: { en: "May 13, 2026", ar: "May 13, 2026" }, blocks: SET_BLOCKS[3] };
byKey["bashans-6"] = { id: "katameros-bashans-6", title: {"en":"6 Bashans","ar":"6 بشنس"}, subtitle: { en: "May 14, 2026", ar: "May 14, 2026" }, blocks: SET_BLOCKS[43] };
byKey["bashans-7"] = { id: "katameros-bashans-7", title: {"en":"7 Bashans","ar":"7 بشنس"}, subtitle: { en: "May 15, 2026", ar: "May 15, 2026" }, blocks: SET_BLOCKS[54] };
byKey["bashans-8"] = { id: "katameros-bashans-8", title: {"en":"8 Bashans","ar":"8 بشنس"}, subtitle: { en: "May 16, 2026", ar: "May 16, 2026" }, blocks: SET_BLOCKS[43] };
byKey["bashans-9"] = { id: "katameros-bashans-9", title: {"en":"9 Bashans","ar":"9 بشنس"}, subtitle: { en: "May 17, 2026", ar: "May 17, 2026" }, blocks: SET_BLOCKS[4] };
byKey["bashans-10"] = { id: "katameros-bashans-10", title: {"en":"10 Bashans","ar":"10 بشنس"}, subtitle: { en: "May 18, 2026", ar: "May 18, 2026" }, blocks: SET_BLOCKS[47] };
byKey["bashans-11"] = { id: "katameros-bashans-11", title: {"en":"11 Bashans","ar":"11 بشنس"}, subtitle: { en: "May 19, 2026", ar: "May 19, 2026" }, blocks: SET_BLOCKS[23] };
byKey["bashans-12"] = { id: "katameros-bashans-12", title: {"en":"12 Bashans","ar":"12 بشنس"}, subtitle: { en: "May 20, 2026", ar: "May 20, 2026" }, blocks: SET_BLOCKS[18] };
byKey["bashans-13"] = { id: "katameros-bashans-13", title: {"en":"13 Bashans","ar":"13 بشنس"}, subtitle: { en: "May 21, 2026", ar: "May 21, 2026" }, blocks: SET_BLOCKS[37] };
byKey["bashans-14"] = { id: "katameros-bashans-14", title: {"en":"14 Bashans","ar":"14 بشنس"}, subtitle: { en: "May 22, 2026", ar: "May 22, 2026" }, blocks: SET_BLOCKS[57] };
byKey["bashans-15"] = { id: "katameros-bashans-15", title: {"en":"15 Bashans","ar":"15 بشنس"}, subtitle: { en: "May 23, 2026", ar: "May 23, 2026" }, blocks: SET_BLOCKS[10] };
byKey["bashans-16"] = { id: "katameros-bashans-16", title: {"en":"16 Bashans","ar":"16 بشنس"}, subtitle: { en: "May 24, 2026", ar: "May 24, 2026" }, blocks: SET_BLOCKS[31] };
byKey["bashans-17"] = { id: "katameros-bashans-17", title: {"en":"17 Bashans","ar":"17 بشنس"}, subtitle: { en: "May 25, 2026", ar: "May 25, 2026" }, blocks: SET_BLOCKS[23] };
byKey["bashans-18"] = { id: "katameros-bashans-18", title: {"en":"18 Bashans","ar":"18 بشنس"}, subtitle: { en: "May 26, 2026", ar: "May 26, 2026" }, blocks: SET_BLOCKS[13] };
byKey["bashans-19"] = { id: "katameros-bashans-19", title: {"en":"19 Bashans","ar":"19 بشنس"}, subtitle: { en: "May 27, 2026", ar: "May 27, 2026" }, blocks: SET_BLOCKS[37] };
byKey["bashans-20"] = { id: "katameros-bashans-20", title: {"en":"20 Bashans","ar":"20 بشنس"}, subtitle: { en: "May 28, 2026", ar: "May 28, 2026" }, blocks: SET_BLOCKS[48] };
byKey["bashans-21"] = { id: "katameros-bashans-21", title: {"en":"21 Bashans","ar":"21 بشنس"}, subtitle: { en: "May 29, 2026", ar: "May 29, 2026" }, blocks: SET_BLOCKS[57] };
byKey["bashans-22"] = { id: "katameros-bashans-22", title: {"en":"22 Bashans","ar":"22 بشنس"}, subtitle: { en: "May 30, 2026", ar: "May 30, 2026" }, blocks: SET_BLOCKS[29] };
byKey["bashans-23"] = { id: "katameros-bashans-23", title: {"en":"23 Bashans","ar":"23 بشنس"}, subtitle: { en: "May 31, 2026", ar: "May 31, 2026" }, blocks: SET_BLOCKS[45] };
byKey["bashans-24"] = { id: "katameros-bashans-24", title: {"en":"24 Bashans","ar":"24 بشنس"}, subtitle: { en: "June 1, 2026", ar: "June 1, 2026" }, blocks: SET_BLOCKS[49] };
byKey["bashans-25"] = { id: "katameros-bashans-25", title: {"en":"25 Bashans","ar":"25 بشنس"}, subtitle: { en: "June 2, 2026", ar: "June 2, 2026" }, blocks: SET_BLOCKS[21] };
byKey["bashans-26"] = { id: "katameros-bashans-26", title: {"en":"26 Bashans","ar":"26 بشنس"}, subtitle: { en: "June 3, 2026", ar: "June 3, 2026" }, blocks: SET_BLOCKS[50] };
byKey["bashans-27"] = { id: "katameros-bashans-27", title: {"en":"27 Bashans","ar":"27 بشنس"}, subtitle: { en: "June 4, 2026", ar: "June 4, 2026" }, blocks: SET_BLOCKS[23] };
byKey["bashans-28"] = { id: "katameros-bashans-28", title: {"en":"28 Bashans","ar":"28 بشنس"}, subtitle: { en: "June 5, 2026", ar: "June 5, 2026" }, blocks: SET_BLOCKS[18] };
byKey["bashans-29"] = { id: "katameros-bashans-29", title: {"en":"29 Bashans","ar":"29 بشنس"}, subtitle: { en: "June 6, 2026", ar: "June 6, 2026" }, blocks: SET_BLOCKS[57] };
byKey["bashans-30"] = { id: "katameros-bashans-30", title: {"en":"30 Bashans","ar":"30 بشنس"}, subtitle: { en: "June 7, 2026", ar: "June 7, 2026" }, blocks: SET_BLOCKS[54] };
byKey["paona-1"] = { id: "katameros-paona-1", title: {"en":"1 Paona","ar":"1 بؤونة"}, subtitle: { en: "June 8, 2026", ar: "June 8, 2026" }, blocks: SET_BLOCKS[29] };
byKey["paona-2"] = { id: "katameros-paona-2", title: {"en":"2 Paona","ar":"2 بؤونة"}, subtitle: { en: "June 9, 2026", ar: "June 9, 2026" }, blocks: SET_BLOCKS[51] };
byKey["paona-3"] = { id: "katameros-paona-3", title: {"en":"3 Paona","ar":"3 بؤونة"}, subtitle: { en: "June 10, 2026", ar: "June 10, 2026" }, blocks: SET_BLOCKS[23] };
byKey["paona-4"] = { id: "katameros-paona-4", title: {"en":"4 Paona","ar":"4 بؤونة"}, subtitle: { en: "June 11, 2026", ar: "June 11, 2026" }, blocks: SET_BLOCKS[17] };
byKey["paona-5"] = { id: "katameros-paona-5", title: {"en":"5 Paona","ar":"5 بؤونة"}, subtitle: { en: "June 12, 2026", ar: "June 12, 2026" }, blocks: SET_BLOCKS[37] };
byKey["paona-6"] = { id: "katameros-paona-6", title: {"en":"6 Paona","ar":"6 بؤونة"}, subtitle: { en: "June 13, 2026", ar: "June 13, 2026" }, blocks: SET_BLOCKS[56] };
byKey["paona-7"] = { id: "katameros-paona-7", title: {"en":"7 Paona","ar":"7 بؤونة"}, subtitle: { en: "June 14, 2026", ar: "June 14, 2026" }, blocks: SET_BLOCKS[43] };
byKey["paona-8"] = { id: "katameros-paona-8", title: {"en":"8 Paona","ar":"8 بؤونة"}, subtitle: { en: "June 15, 2026", ar: "June 15, 2026" }, blocks: SET_BLOCKS[49] };
byKey["paona-9"] = { id: "katameros-paona-9", title: {"en":"9 Paona","ar":"9 بؤونة"}, subtitle: { en: "June 16, 2026", ar: "June 16, 2026" }, blocks: SET_BLOCKS[3] };
byKey["paona-10"] = { id: "katameros-paona-10", title: {"en":"10 Paona","ar":"10 بؤونة"}, subtitle: { en: "June 17, 2026", ar: "June 17, 2026" }, blocks: SET_BLOCKS[19] };
byKey["paona-11"] = { id: "katameros-paona-11", title: {"en":"11 Paona","ar":"11 بؤونة"}, subtitle: { en: "June 18, 2026", ar: "June 18, 2026" }, blocks: SET_BLOCKS[44] };
byKey["paona-12"] = { id: "katameros-paona-12", title: {"en":"12 Paona","ar":"12 بؤونة"}, subtitle: { en: "June 19, 2026", ar: "June 19, 2026" }, blocks: SET_BLOCKS[51] };
byKey["paona-13"] = { id: "katameros-paona-13", title: {"en":"13 Paona","ar":"13 بؤونة"}, subtitle: { en: "June 20, 2026", ar: "June 20, 2026" }, blocks: SET_BLOCKS[67] };
byKey["paona-14"] = { id: "katameros-paona-14", title: {"en":"14 Paona","ar":"14 بؤونة"}, subtitle: { en: "June 21, 2026", ar: "June 21, 2026" }, blocks: SET_BLOCKS[23] };
byKey["paona-15"] = { id: "katameros-paona-15", title: {"en":"15 Paona","ar":"15 بؤونة"}, subtitle: { en: "June 22, 2026", ar: "June 22, 2026" }, blocks: SET_BLOCKS[17] };
byKey["paona-16"] = { id: "katameros-paona-16", title: {"en":"16 Paona","ar":"16 بؤونة"}, subtitle: { en: "June 23, 2026", ar: "June 23, 2026" }, blocks: SET_BLOCKS[52] };
byKey["paona-17"] = { id: "katameros-paona-17", title: {"en":"17 Paona","ar":"17 بؤونة"}, subtitle: { en: "June 24, 2026", ar: "June 24, 2026" }, blocks: SET_BLOCKS[37] };
byKey["paona-18"] = { id: "katameros-paona-18", title: {"en":"18 Paona","ar":"18 بؤونة"}, subtitle: { en: "June 25, 2026", ar: "June 25, 2026" }, blocks: SET_BLOCKS[24] };
byKey["paona-19"] = { id: "katameros-paona-19", title: {"en":"19 Paona","ar":"19 بؤونة"}, subtitle: { en: "June 26, 2026", ar: "June 26, 2026" }, blocks: SET_BLOCKS[43] };
byKey["paona-20"] = { id: "katameros-paona-20", title: {"en":"20 Paona","ar":"20 بؤونة"}, subtitle: { en: "June 27, 2026", ar: "June 27, 2026" }, blocks: SET_BLOCKS[3] };
byKey["paona-21"] = { id: "katameros-paona-21", title: {"en":"21 Paona","ar":"21 بؤونة"}, subtitle: { en: "June 28, 2026", ar: "June 28, 2026" }, blocks: SET_BLOCKS[46] };
byKey["paona-22"] = { id: "katameros-paona-22", title: {"en":"22 Paona","ar":"22 بؤونة"}, subtitle: { en: "June 29, 2026", ar: "June 29, 2026" }, blocks: SET_BLOCKS[19] };
byKey["paona-23"] = { id: "katameros-paona-23", title: {"en":"23 Paona","ar":"23 بؤونة"}, subtitle: { en: "June 30, 2026", ar: "June 30, 2026" }, blocks: SET_BLOCKS[37] };
byKey["paona-24"] = { id: "katameros-paona-24", title: {"en":"24 Paona","ar":"24 بؤونة"}, subtitle: { en: "July 1, 2026", ar: "July 1, 2026" }, blocks: SET_BLOCKS[57] };
byKey["paona-25"] = { id: "katameros-paona-25", title: {"en":"25 Paona","ar":"25 بؤونة"}, subtitle: { en: "July 2, 2026", ar: "July 2, 2026" }, blocks: SET_BLOCKS[29] };
byKey["paona-26"] = { id: "katameros-paona-26", title: {"en":"26 Paona","ar":"26 بؤونة"}, subtitle: { en: "July 3, 2026", ar: "July 3, 2026" }, blocks: SET_BLOCKS[3] };
byKey["paona-27"] = { id: "katameros-paona-27", title: {"en":"27 Paona","ar":"27 بؤونة"}, subtitle: { en: "July 4, 2026", ar: "July 4, 2026" }, blocks: SET_BLOCKS[45] };
byKey["paona-28"] = { id: "katameros-paona-28", title: {"en":"28 Paona","ar":"28 بؤونة"}, subtitle: { en: "July 5, 2026", ar: "July 5, 2026" }, blocks: SET_BLOCKS[54] };
byKey["paona-29"] = { id: "katameros-paona-29", title: {"en":"29 Paona","ar":"29 بؤونة"}, subtitle: { en: "July 6, 2026", ar: "July 6, 2026" }, blocks: SET_BLOCKS[48] };
byKey["paona-30"] = { id: "katameros-paona-30", title: {"en":"30 Paona","ar":"30 بؤونة"}, subtitle: { en: "July 7, 2026", ar: "July 7, 2026" }, blocks: SET_BLOCKS[53] };
byKey["epep-1"] = { id: "katameros-epep-1", title: {"en":"1 Epep","ar":"1 أبيب"}, subtitle: { en: "July 8, 2026", ar: "July 8, 2026" }, blocks: SET_BLOCKS[39] };
byKey["epep-2"] = { id: "katameros-epep-2", title: {"en":"2 Epep","ar":"2 أبيب"}, subtitle: { en: "July 9, 2026", ar: "July 9, 2026" }, blocks: SET_BLOCKS[45] };
byKey["epep-3"] = { id: "katameros-epep-3", title: {"en":"3 Epep","ar":"3 أبيب"}, subtitle: { en: "July 10, 2026", ar: "July 10, 2026" }, blocks: SET_BLOCKS[54] };
byKey["epep-4"] = { id: "katameros-epep-4", title: {"en":"4 Epep","ar":"4 أبيب"}, subtitle: { en: "July 11, 2026", ar: "July 11, 2026" }, blocks: SET_BLOCKS[17] };
byKey["epep-5"] = { id: "katameros-epep-5", title: {"en":"5 Epep","ar":"5 أبيب"}, subtitle: { en: "July 12, 2026", ar: "July 12, 2026" }, blocks: SET_BLOCKS[55] };
byKey["epep-6"] = { id: "katameros-epep-6", title: {"en":"6 Epep","ar":"6 أبيب"}, subtitle: { en: "July 13, 2026", ar: "July 13, 2026" }, blocks: SET_BLOCKS[29] };
byKey["epep-7"] = { id: "katameros-epep-7", title: {"en":"7 Epep","ar":"7 أبيب"}, subtitle: { en: "July 14, 2026", ar: "July 14, 2026" }, blocks: SET_BLOCKS[40] };
byKey["epep-8"] = { id: "katameros-epep-8", title: {"en":"8 Epep","ar":"8 أبيب"}, subtitle: { en: "July 15, 2026", ar: "July 15, 2026" }, blocks: SET_BLOCKS[13] };
byKey["epep-9"] = { id: "katameros-epep-9", title: {"en":"9 Epep","ar":"9 أبيب"}, subtitle: { en: "July 16, 2026", ar: "July 16, 2026" }, blocks: SET_BLOCKS[45] };
byKey["epep-10"] = { id: "katameros-epep-10", title: {"en":"10 Epep","ar":"10 أبيب"}, subtitle: { en: "July 17, 2026", ar: "July 17, 2026" }, blocks: SET_BLOCKS[23] };
byKey["epep-11"] = { id: "katameros-epep-11", title: {"en":"11 Epep","ar":"11 أبيب"}, subtitle: { en: "July 18, 2026", ar: "July 18, 2026" }, blocks: SET_BLOCKS[44] };
byKey["epep-12"] = { id: "katameros-epep-12", title: {"en":"12 Epep","ar":"12 أبيب"}, subtitle: { en: "July 19, 2026", ar: "July 19, 2026" }, blocks: SET_BLOCKS[17] };
byKey["epep-13"] = { id: "katameros-epep-13", title: {"en":"13 Epep","ar":"13 أبيب"}, subtitle: { en: "July 20, 2026", ar: "July 20, 2026" }, blocks: SET_BLOCKS[23] };
byKey["epep-14"] = { id: "katameros-epep-14", title: {"en":"14 Epep","ar":"14 أبيب"}, subtitle: { en: "July 21, 2026", ar: "July 21, 2026" }, blocks: SET_BLOCKS[13] };
byKey["epep-15"] = { id: "katameros-epep-15", title: {"en":"15 Epep","ar":"15 أبيب"}, subtitle: { en: "July 22, 2026", ar: "July 22, 2026" }, blocks: SET_BLOCKS[57] };
byKey["epep-16"] = { id: "katameros-epep-16", title: {"en":"16 Epep","ar":"16 أبيب"}, subtitle: { en: "July 23, 2026", ar: "July 23, 2026" }, blocks: SET_BLOCKS[31] };
byKey["epep-17"] = { id: "katameros-epep-17", title: {"en":"17 Epep","ar":"17 أبيب"}, subtitle: { en: "July 24, 2026", ar: "July 24, 2026" }, blocks: SET_BLOCKS[39] };
byKey["epep-18"] = { id: "katameros-epep-18", title: {"en":"18 Epep","ar":"18 أبيب"}, subtitle: { en: "July 25, 2026", ar: "July 25, 2026" }, blocks: SET_BLOCKS[55] };
byKey["epep-19"] = { id: "katameros-epep-19", title: {"en":"19 Epep","ar":"19 أبيب"}, subtitle: { en: "July 26, 2026", ar: "July 26, 2026" }, blocks: SET_BLOCKS[19] };
byKey["epep-20"] = { id: "katameros-epep-20", title: {"en":"20 Epep","ar":"20 أبيب"}, subtitle: { en: "July 27, 2026", ar: "July 27, 2026" }, blocks: SET_BLOCKS[56] };
byKey["epep-21"] = { id: "katameros-epep-21", title: {"en":"21 Epep","ar":"21 أبيب"}, subtitle: { en: "July 28, 2026", ar: "July 28, 2026" }, blocks: SET_BLOCKS[41] };
byKey["epep-22"] = { id: "katameros-epep-22", title: {"en":"22 Epep","ar":"22 أبيب"}, subtitle: { en: "July 29, 2026", ar: "July 29, 2026" }, blocks: SET_BLOCKS[44] };
byKey["epep-23"] = { id: "katameros-epep-23", title: {"en":"23 Epep","ar":"23 أبيب"}, subtitle: { en: "July 30, 2026", ar: "July 30, 2026" }, blocks: SET_BLOCKS[22] };
byKey["epep-24"] = { id: "katameros-epep-24", title: {"en":"24 Epep","ar":"24 أبيب"}, subtitle: { en: "July 31, 2026", ar: "July 31, 2026" }, blocks: SET_BLOCKS[17] };
byKey["epep-25"] = { id: "katameros-epep-25", title: {"en":"25 Epep","ar":"25 أبيب"}, subtitle: { en: "August 1, 2026", ar: "August 1, 2026" }, blocks: SET_BLOCKS[21] };
byKey["epep-26"] = { id: "katameros-epep-26", title: {"en":"26 Epep","ar":"26 أبيب"}, subtitle: { en: "August 2, 2026", ar: "August 2, 2026" }, blocks: SET_BLOCKS[3] };
byKey["epep-27"] = { id: "katameros-epep-27", title: {"en":"27 Epep","ar":"27 أبيب"}, subtitle: { en: "August 3, 2026", ar: "August 3, 2026" }, blocks: SET_BLOCKS[43] };
byKey["epep-28"] = { id: "katameros-epep-28", title: {"en":"28 Epep","ar":"28 أبيب"}, subtitle: { en: "August 4, 2026", ar: "August 4, 2026" }, blocks: SET_BLOCKS[39] };
byKey["epep-29"] = { id: "katameros-epep-29", title: {"en":"29 Epep","ar":"29 أبيب"}, subtitle: { en: "August 5, 2026", ar: "August 5, 2026" }, blocks: SET_BLOCKS[55] };
byKey["epep-30"] = { id: "katameros-epep-30", title: {"en":"30 Epep","ar":"30 أبيب"}, subtitle: { en: "August 6, 2026", ar: "August 6, 2026" }, blocks: SET_BLOCKS[19] };
byKey["mesra-1"] = { id: "katameros-mesra-1", title: {"en":"1 Mesra","ar":"1 مسرى"}, subtitle: { en: "August 7, 2026", ar: "August 7, 2026" }, blocks: SET_BLOCKS[17] };
byKey["mesra-2"] = { id: "katameros-mesra-2", title: {"en":"2 Mesra","ar":"2 مسرى"}, subtitle: { en: "August 8, 2026", ar: "August 8, 2026" }, blocks: SET_BLOCKS[39] };
byKey["mesra-3"] = { id: "katameros-mesra-3", title: {"en":"3 Mesra","ar":"3 مسرى"}, subtitle: { en: "August 9, 2026", ar: "August 9, 2026" }, blocks: SET_BLOCKS[57] };
byKey["mesra-4"] = { id: "katameros-mesra-4", title: {"en":"4 Mesra","ar":"4 مسرى"}, subtitle: { en: "August 10, 2026", ar: "August 10, 2026" }, blocks: SET_BLOCKS[3] };
byKey["mesra-5"] = { id: "katameros-mesra-5", title: {"en":"5 Mesra","ar":"5 مسرى"}, subtitle: { en: "August 11, 2026", ar: "August 11, 2026" }, blocks: SET_BLOCKS[38] };
byKey["mesra-6"] = { id: "katameros-mesra-6", title: {"en":"6 Mesra","ar":"6 مسرى"}, subtitle: { en: "August 12, 2026", ar: "August 12, 2026" }, blocks: SET_BLOCKS[39] };
byKey["mesra-7"] = { id: "katameros-mesra-7", title: {"en":"7 Mesra","ar":"7 مسرى"}, subtitle: { en: "August 13, 2026", ar: "August 13, 2026" }, blocks: SET_BLOCKS[9] };
byKey["mesra-8"] = { id: "katameros-mesra-8", title: {"en":"8 Mesra","ar":"8 مسرى"}, subtitle: { en: "August 14, 2026", ar: "August 14, 2026" }, blocks: SET_BLOCKS[47] };
byKey["mesra-9"] = { id: "katameros-mesra-9", title: {"en":"9 Mesra","ar":"9 مسرى"}, subtitle: { en: "August 15, 2026", ar: "August 15, 2026" }, blocks: SET_BLOCKS[17] };
byKey["mesra-10"] = { id: "katameros-mesra-10", title: {"en":"10 Mesra","ar":"10 مسرى"}, subtitle: { en: "August 16, 2026", ar: "August 16, 2026" }, blocks: SET_BLOCKS[22] };
byKey["mesra-11"] = { id: "katameros-mesra-11", title: {"en":"11 Mesra","ar":"11 مسرى"}, subtitle: { en: "August 17, 2026", ar: "August 17, 2026" }, blocks: SET_BLOCKS[23] };
byKey["mesra-12"] = { id: "katameros-mesra-12", title: {"en":"12 Mesra","ar":"12 مسرى"}, subtitle: { en: "August 18, 2026", ar: "August 18, 2026" }, blocks: SET_BLOCKS[5] };
byKey["mesra-13"] = { id: "katameros-mesra-13", title: {"en":"13 Mesra","ar":"13 مسرى"}, subtitle: { en: "August 19, 2026", ar: "August 19, 2026" }, blocks: SET_BLOCKS[58] };
byKey["mesra-14"] = { id: "katameros-mesra-14", title: {"en":"14 Mesra","ar":"14 مسرى"}, subtitle: { en: "August 20, 2026", ar: "August 20, 2026" }, blocks: SET_BLOCKS[18] };
byKey["mesra-15"] = { id: "katameros-mesra-15", title: {"en":"15 Mesra","ar":"15 مسرى"}, subtitle: { en: "August 21, 2026", ar: "August 21, 2026" }, blocks: SET_BLOCKS[39] };
byKey["mesra-16"] = { id: "katameros-mesra-16", title: {"en":"16 Mesra","ar":"16 مسرى"}, subtitle: { en: "August 22, 2026", ar: "August 22, 2026" }, blocks: SET_BLOCKS[46] };
byKey["mesra-17"] = { id: "katameros-mesra-17", title: {"en":"17 Mesra","ar":"17 مسرى"}, subtitle: { en: "August 23, 2026", ar: "August 23, 2026" }, blocks: SET_BLOCKS[59] };
byKey["mesra-18"] = { id: "katameros-mesra-18", title: {"en":"18 Mesra","ar":"18 مسرى"}, subtitle: { en: "August 24, 2026", ar: "August 24, 2026" }, blocks: SET_BLOCKS[54] };
byKey["mesra-19"] = { id: "katameros-mesra-19", title: {"en":"19 Mesra","ar":"19 مسرى"}, subtitle: { en: "August 25, 2026", ar: "August 25, 2026" }, blocks: SET_BLOCKS[13] };
byKey["mesra-20"] = { id: "katameros-mesra-20", title: {"en":"20 Mesra","ar":"20 مسرى"}, subtitle: { en: "August 26, 2026", ar: "August 26, 2026" }, blocks: SET_BLOCKS[19] };
byKey["mesra-21"] = { id: "katameros-mesra-21", title: {"en":"21 Mesra","ar":"21 مسرى"}, subtitle: { en: "August 27, 2026", ar: "August 27, 2026" }, blocks: SET_BLOCKS[39] };
byKey["mesra-22"] = { id: "katameros-mesra-22", title: {"en":"22 Mesra","ar":"22 مسرى"}, subtitle: { en: "August 28, 2026", ar: "August 28, 2026" }, blocks: SET_BLOCKS[3] };
byKey["mesra-23"] = { id: "katameros-mesra-23", title: {"en":"23 Mesra","ar":"23 مسرى"}, subtitle: { en: "August 29, 2026", ar: "August 29, 2026" }, blocks: SET_BLOCKS[43] };
byKey["mesra-24"] = { id: "katameros-mesra-24", title: {"en":"24 Mesra","ar":"24 مسرى"}, subtitle: { en: "August 30, 2026", ar: "August 30, 2026" }, blocks: SET_BLOCKS[23] };
byKey["mesra-25"] = { id: "katameros-mesra-25", title: {"en":"25 Mesra","ar":"25 مسرى"}, subtitle: { en: "August 31, 2026", ar: "August 31, 2026" }, blocks: SET_BLOCKS[60] };
byKey["mesra-26"] = { id: "katameros-mesra-26", title: {"en":"26 Mesra","ar":"26 مسرى"}, subtitle: { en: "September 1, 2026", ar: "September 1, 2026" }, blocks: SET_BLOCKS[61] };
byKey["mesra-27"] = { id: "katameros-mesra-27", title: {"en":"27 Mesra","ar":"27 مسرى"}, subtitle: { en: "September 2, 2026", ar: "September 2, 2026" }, blocks: SET_BLOCKS[43] };
byKey["mesra-28"] = { id: "katameros-mesra-28", title: {"en":"28 Mesra","ar":"28 مسرى"}, subtitle: { en: "September 3, 2026", ar: "September 3, 2026" }, blocks: SET_BLOCKS[62] };
byKey["mesra-29"] = { id: "katameros-mesra-29", title: {"en":"29 Mesra","ar":"29 مسرى"}, subtitle: { en: "September 4, 2026", ar: "September 4, 2026" }, blocks: SET_BLOCKS[63] };
byKey["mesra-30"] = { id: "katameros-mesra-30", title: {"en":"30 Mesra","ar":"30 مسرى"}, subtitle: { en: "September 5, 2026", ar: "September 5, 2026" }, blocks: SET_BLOCKS[64] };
byKey["nasie-1"] = { id: "katameros-nasie-1", title: {"en":"1 Nasie","ar":"1 النسيء"}, subtitle: { en: "September 6, 2026", ar: "September 6, 2026" }, blocks: SET_BLOCKS[65] };
byKey["nasie-2"] = { id: "katameros-nasie-2", title: {"en":"2 Nasie","ar":"2 النسيء"}, subtitle: { en: "September 7, 2026", ar: "September 7, 2026" }, blocks: SET_BLOCKS[66] };
byKey["nasie-3"] = { id: "katameros-nasie-3", title: {"en":"3 Nasie","ar":"3 النسيء"}, subtitle: { en: "September 8, 2026", ar: "September 8, 2026" }, blocks: SET_BLOCKS[67] };
byKey["nasie-4"] = { id: "katameros-nasie-4", title: {"en":"4 Nasie","ar":"4 النسيء"}, subtitle: { en: "September 9, 2026", ar: "September 9, 2026" }, blocks: SET_BLOCKS[68] };
byKey["nasie-5"] = { id: "katameros-nasie-5", title: {"en":"5 Nasie","ar":"5 النسيء"}, subtitle: { en: "September 10, 2026", ar: "September 10, 2026" }, blocks: SET_BLOCKS[23] };
byKey["nasie-6"] = { id: "katameros-nasie-6", title: {"en":"6 Nasie","ar":"6 النسيء"}, subtitle: { en: "September 11, 2026", ar: "September 11, 2026" }, blocks: SET_BLOCKS[69] };
byKey["feast-feast-of-the-cross"] = { id: "katameros-feast-feast-of-the-cross", title: {"en":"Feast of the Cross","ar":"عيد الصليب"}, subtitle: { en: "17 Tout · September 27, 2025", ar: "17 توت · September 27, 2025" }, blocks: SET_BLOCKS[5] };
byKey["feast-nativity"] = { id: "katameros-feast-nativity", title: {"en":"Nativity","ar":"عيد الميلاد"}, subtitle: { en: "29 Kiahk · January 7, 2026", ar: "29 كيهك · January 7, 2026" }, blocks: SET_BLOCKS[27] };
byKey["feast-circumcision-of-christ"] = { id: "katameros-feast-circumcision-of-christ", title: {"en":"Circumcision of Christ","ar":"عيد الختان"}, subtitle: { en: "6 Toba · January 14, 2026", ar: "6 طوبة · January 14, 2026" }, blocks: SET_BLOCKS[32] };
byKey["feast-theophany"] = { id: "katameros-feast-theophany", title: {"en":"Theophany","ar":"عيد الغطاس"}, subtitle: { en: "11 Toba · January 19, 2026", ar: "11 طوبة · January 19, 2026" }, blocks: SET_BLOCKS[34] };
byKey["feast-wedding-at-cana"] = { id: "katameros-feast-wedding-at-cana", title: {"en":"Wedding at Cana","ar":"عرس قانا الجليل"}, subtitle: { en: "13 Toba · January 21, 2026", ar: "13 طوبة · January 21, 2026" }, blocks: SET_BLOCKS[36] };
byKey["feast-entry-of-christ-into-the-temple"] = { id: "katameros-feast-entry-of-christ-into-the-temple", title: {"en":"Entry of Christ into the Temple","ar":"دخول المسيح إلى الهيكل"}, subtitle: { en: "8 Amshir · February 15, 2026", ar: "8 أمشير · February 15, 2026" }, blocks: SET_BLOCKS[2] };
byKey["feast-feast-of-the-cross"] = { id: "katameros-feast-feast-of-the-cross", title: {"en":"Feast of the Cross","ar":"عيد الصليب"}, subtitle: { en: "10 Baramhat · March 19, 2026", ar: "10 برمهات · March 19, 2026" }, blocks: SET_BLOCKS[5] };
byKey["feast-palm-sunday"] = { id: "katameros-feast-palm-sunday", title: {"en":"Palm Sunday","ar":"أحد الشعانين"}, subtitle: { en: "27 Baramhat · April 5, 2026", ar: "27 برمهات · April 5, 2026" }, blocks: SET_BLOCKS[13] };
byKey["feast-annunciation"] = { id: "katameros-feast-annunciation", title: {"en":"Annunciation","ar":"عيد البشارة"}, subtitle: { en: "29 Baramhat · April 7, 2026", ar: "29 برمهات · April 7, 2026" }, blocks: SET_BLOCKS[42] };
byKey["feast-covenant-thursday"] = { id: "katameros-feast-covenant-thursday", title: {"en":"Covenant Thursday","ar":"خميس العهد"}, subtitle: { en: "1 Baramouda · April 9, 2026", ar: "1 برمودة · April 9, 2026" }, blocks: SET_BLOCKS[48] };
byKey["feast-feast-of-the-resurrection"] = { id: "katameros-feast-feast-of-the-resurrection", title: {"en":"Feast of the Resurrection","ar":"عيد القيامة"}, subtitle: { en: "4 Baramouda · April 12, 2026", ar: "4 برمودة · April 12, 2026" }, blocks: SET_BLOCKS[19] };
byKey["feast-thomas-sunday"] = { id: "katameros-feast-thomas-sunday", title: {"en":"Thomas Sunday","ar":"أحد توما"}, subtitle: { en: "11 Baramouda · April 19, 2026", ar: "11 برمودة · April 19, 2026" }, blocks: SET_BLOCKS[39] };
byKey["feast-ascension"] = { id: "katameros-feast-ascension", title: {"en":"Ascension","ar":"عيد الصعود"}, subtitle: { en: "13 Bashans · May 21, 2026", ar: "13 بشنس · May 21, 2026" }, blocks: SET_BLOCKS[37] };
byKey["feast-pentecost"] = { id: "katameros-feast-pentecost", title: {"en":"Pentecost","ar":"عيد العنصرة"}, subtitle: { en: "23 Bashans · May 31, 2026", ar: "23 بشنس · May 31, 2026" }, blocks: SET_BLOCKS[45] };
byKey["feast-entry-of-christ-into-egypt"] = { id: "katameros-feast-entry-of-christ-into-egypt", title: {"en":"Entry of Christ into Egypt","ar":"دخول المسيح أرض مصر"}, subtitle: { en: "24 Bashans · June 1, 2026", ar: "24 بشنس · June 1, 2026" }, blocks: SET_BLOCKS[49] };
byKey["feast-transfiguration"] = { id: "katameros-feast-transfiguration", title: {"en":"Transfiguration","ar":"عيد التجلي"}, subtitle: { en: "13 Mesra · August 19, 2026", ar: "13 مسرى · August 19, 2026" }, blocks: SET_BLOCKS[58] };

export const sundaysDocs: CRDocument[] = [
  byKey["tout-4"],
  byKey["tout-11"],
  byKey["tout-18"],
  byKey["tout-25"],
  byKey["baba-2"],
  byKey["baba-9"],
  byKey["baba-16"],
  byKey["baba-23"],
  byKey["baba-30"],
  byKey["hator-7"],
  byKey["hator-14"],
  byKey["hator-21"],
  byKey["hator-28"],
  byKey["kiahk-5"],
  byKey["kiahk-12"],
  byKey["kiahk-19"],
  byKey["kiahk-26"],
  byKey["toba-3"],
  byKey["toba-10"],
  byKey["toba-17"],
  byKey["toba-24"],
  byKey["amshir-1"],
  byKey["amshir-8"],
  byKey["amshir-15"],
  byKey["amshir-22"],
  byKey["amshir-29"],
  byKey["baramhat-6"],
  byKey["baramhat-13"],
  byKey["baramhat-20"],
  byKey["baramhat-27"],
  byKey["baramouda-4"],
  byKey["baramouda-11"],
  byKey["baramouda-18"],
  byKey["baramouda-25"],
  byKey["bashans-2"],
  byKey["bashans-9"],
  byKey["bashans-16"],
  byKey["bashans-23"],
  byKey["bashans-30"],
  byKey["paona-7"],
  byKey["paona-14"],
  byKey["paona-21"],
  byKey["paona-28"],
  byKey["epep-5"],
  byKey["epep-12"],
  byKey["epep-19"],
  byKey["epep-26"],
  byKey["mesra-3"],
  byKey["mesra-10"],
  byKey["mesra-17"],
  byKey["mesra-24"],
  byKey["nasie-1"],
];

export const weekdaysDocs: CRDocument[] = [
  byKey["tout-1"],
  byKey["tout-2"],
  byKey["tout-3"],
  byKey["tout-5"],
  byKey["tout-6"],
  byKey["tout-7"],
  byKey["tout-8"],
  byKey["tout-9"],
  byKey["tout-10"],
  byKey["tout-12"],
  byKey["tout-13"],
  byKey["tout-14"],
  byKey["tout-15"],
  byKey["tout-16"],
  byKey["tout-17"],
  byKey["tout-19"],
  byKey["tout-20"],
  byKey["tout-21"],
  byKey["tout-22"],
  byKey["tout-23"],
  byKey["tout-24"],
  byKey["tout-26"],
  byKey["tout-27"],
  byKey["tout-28"],
  byKey["tout-29"],
  byKey["tout-30"],
  byKey["baba-1"],
  byKey["baba-3"],
  byKey["baba-4"],
  byKey["baba-5"],
  byKey["baba-6"],
  byKey["baba-7"],
  byKey["baba-8"],
  byKey["baba-10"],
  byKey["baba-11"],
  byKey["baba-12"],
  byKey["baba-13"],
  byKey["baba-14"],
  byKey["baba-15"],
  byKey["baba-17"],
  byKey["baba-18"],
  byKey["baba-19"],
  byKey["baba-20"],
  byKey["baba-21"],
  byKey["baba-22"],
  byKey["baba-24"],
  byKey["baba-25"],
  byKey["baba-26"],
  byKey["baba-27"],
  byKey["baba-28"],
  byKey["baba-29"],
  byKey["hator-1"],
  byKey["hator-2"],
  byKey["hator-3"],
  byKey["hator-4"],
  byKey["hator-5"],
  byKey["hator-6"],
  byKey["hator-8"],
  byKey["hator-9"],
  byKey["hator-10"],
  byKey["hator-11"],
  byKey["hator-12"],
  byKey["hator-13"],
  byKey["hator-15"],
  byKey["hator-16"],
  byKey["hator-17"],
  byKey["hator-18"],
  byKey["hator-19"],
  byKey["hator-20"],
  byKey["hator-22"],
  byKey["hator-23"],
  byKey["hator-24"],
  byKey["hator-25"],
  byKey["hator-26"],
  byKey["hator-27"],
  byKey["hator-29"],
  byKey["hator-30"],
  byKey["kiahk-1"],
  byKey["kiahk-2"],
  byKey["kiahk-3"],
  byKey["kiahk-4"],
  byKey["kiahk-6"],
  byKey["kiahk-7"],
  byKey["kiahk-8"],
  byKey["kiahk-9"],
  byKey["kiahk-10"],
  byKey["kiahk-11"],
  byKey["kiahk-13"],
  byKey["kiahk-14"],
  byKey["kiahk-15"],
  byKey["kiahk-16"],
  byKey["kiahk-17"],
  byKey["kiahk-18"],
  byKey["kiahk-20"],
  byKey["kiahk-21"],
  byKey["kiahk-22"],
  byKey["kiahk-23"],
  byKey["kiahk-24"],
  byKey["kiahk-25"],
  byKey["kiahk-27"],
  byKey["kiahk-28"],
  byKey["kiahk-29"],
  byKey["kiahk-30"],
  byKey["toba-1"],
  byKey["toba-2"],
  byKey["toba-4"],
  byKey["toba-5"],
  byKey["toba-6"],
  byKey["toba-7"],
  byKey["toba-8"],
  byKey["toba-9"],
  byKey["toba-11"],
  byKey["toba-12"],
  byKey["toba-13"],
  byKey["toba-14"],
  byKey["toba-15"],
  byKey["toba-16"],
  byKey["toba-18"],
  byKey["toba-19"],
  byKey["toba-20"],
  byKey["toba-21"],
  byKey["toba-22"],
  byKey["toba-23"],
  byKey["toba-25"],
  byKey["toba-26"],
  byKey["toba-27"],
  byKey["toba-28"],
  byKey["toba-29"],
  byKey["toba-30"],
  byKey["amshir-2"],
  byKey["amshir-3"],
  byKey["amshir-4"],
  byKey["amshir-5"],
  byKey["amshir-6"],
  byKey["amshir-7"],
  byKey["baramouda-5"],
  byKey["baramouda-6"],
  byKey["baramouda-7"],
  byKey["baramouda-8"],
  byKey["baramouda-9"],
  byKey["baramouda-10"],
  byKey["baramouda-12"],
  byKey["baramouda-13"],
  byKey["baramouda-14"],
  byKey["baramouda-15"],
  byKey["baramouda-16"],
  byKey["baramouda-17"],
  byKey["baramouda-19"],
  byKey["baramouda-20"],
  byKey["baramouda-21"],
  byKey["baramouda-22"],
  byKey["baramouda-23"],
  byKey["baramouda-24"],
  byKey["baramouda-26"],
  byKey["baramouda-27"],
  byKey["baramouda-28"],
  byKey["baramouda-29"],
  byKey["baramouda-30"],
  byKey["bashans-1"],
  byKey["bashans-3"],
  byKey["bashans-4"],
  byKey["bashans-5"],
  byKey["bashans-6"],
  byKey["bashans-7"],
  byKey["bashans-8"],
  byKey["bashans-10"],
  byKey["bashans-11"],
  byKey["bashans-12"],
  byKey["bashans-13"],
  byKey["bashans-14"],
  byKey["bashans-15"],
  byKey["bashans-17"],
  byKey["bashans-18"],
  byKey["bashans-19"],
  byKey["bashans-20"],
  byKey["bashans-21"],
  byKey["bashans-22"],
  byKey["bashans-24"],
  byKey["bashans-25"],
  byKey["bashans-26"],
  byKey["bashans-27"],
  byKey["bashans-28"],
  byKey["bashans-29"],
  byKey["paona-1"],
  byKey["paona-2"],
  byKey["paona-3"],
  byKey["paona-4"],
  byKey["paona-5"],
  byKey["paona-6"],
  byKey["paona-8"],
  byKey["paona-9"],
  byKey["paona-10"],
  byKey["paona-11"],
  byKey["paona-12"],
  byKey["paona-13"],
  byKey["paona-15"],
  byKey["paona-16"],
  byKey["paona-17"],
  byKey["paona-18"],
  byKey["paona-19"],
  byKey["paona-20"],
  byKey["paona-22"],
  byKey["paona-23"],
  byKey["paona-24"],
  byKey["paona-25"],
  byKey["paona-26"],
  byKey["paona-27"],
  byKey["paona-29"],
  byKey["paona-30"],
  byKey["epep-1"],
  byKey["epep-2"],
  byKey["epep-3"],
  byKey["epep-4"],
  byKey["epep-6"],
  byKey["epep-7"],
  byKey["epep-8"],
  byKey["epep-9"],
  byKey["epep-10"],
  byKey["epep-11"],
  byKey["epep-13"],
  byKey["epep-14"],
  byKey["epep-15"],
  byKey["epep-16"],
  byKey["epep-17"],
  byKey["epep-18"],
  byKey["epep-20"],
  byKey["epep-21"],
  byKey["epep-22"],
  byKey["epep-23"],
  byKey["epep-24"],
  byKey["epep-25"],
  byKey["epep-27"],
  byKey["epep-28"],
  byKey["epep-29"],
  byKey["epep-30"],
  byKey["mesra-1"],
  byKey["mesra-2"],
  byKey["mesra-4"],
  byKey["mesra-5"],
  byKey["mesra-6"],
  byKey["mesra-7"],
  byKey["mesra-8"],
  byKey["mesra-9"],
  byKey["mesra-11"],
  byKey["mesra-12"],
  byKey["mesra-13"],
  byKey["mesra-14"],
  byKey["mesra-15"],
  byKey["mesra-16"],
  byKey["mesra-18"],
  byKey["mesra-19"],
  byKey["mesra-20"],
  byKey["mesra-21"],
  byKey["mesra-22"],
  byKey["mesra-23"],
  byKey["mesra-25"],
  byKey["mesra-26"],
  byKey["mesra-27"],
  byKey["mesra-28"],
  byKey["mesra-29"],
  byKey["mesra-30"],
  byKey["nasie-2"],
  byKey["nasie-3"],
  byKey["nasie-4"],
  byKey["nasie-5"],
  byKey["nasie-6"],
];

export const fastDocs: CRDocument[] = [
  byKey["amshir-9"],
  byKey["amshir-10"],
  byKey["amshir-11"],
  byKey["amshir-12"],
  byKey["amshir-13"],
  byKey["amshir-14"],
  byKey["amshir-15"],
  byKey["amshir-16"],
  byKey["amshir-17"],
  byKey["amshir-18"],
  byKey["amshir-19"],
  byKey["amshir-20"],
  byKey["amshir-21"],
  byKey["amshir-22"],
  byKey["amshir-23"],
  byKey["amshir-24"],
  byKey["amshir-25"],
  byKey["amshir-26"],
  byKey["amshir-27"],
  byKey["amshir-28"],
  byKey["amshir-29"],
  byKey["amshir-30"],
  byKey["baramhat-1"],
  byKey["baramhat-2"],
  byKey["baramhat-3"],
  byKey["baramhat-4"],
  byKey["baramhat-5"],
  byKey["baramhat-6"],
  byKey["baramhat-7"],
  byKey["baramhat-8"],
  byKey["baramhat-9"],
  byKey["baramhat-10"],
  byKey["baramhat-11"],
  byKey["baramhat-12"],
  byKey["baramhat-13"],
  byKey["baramhat-14"],
  byKey["baramhat-15"],
  byKey["baramhat-16"],
  byKey["baramhat-17"],
  byKey["baramhat-18"],
  byKey["baramhat-19"],
  byKey["baramhat-20"],
  byKey["baramhat-21"],
  byKey["baramhat-22"],
  byKey["baramhat-23"],
  byKey["baramhat-24"],
  byKey["baramhat-25"],
  byKey["baramhat-26"],
  byKey["baramhat-27"],
  byKey["baramhat-28"],
  byKey["baramhat-29"],
  byKey["baramhat-30"],
  byKey["baramouda-1"],
  byKey["baramouda-2"],
  byKey["baramouda-3"],
];

export const feastsDocs: CRDocument[] = [
  byKey["feast-feast-of-the-cross"],
  byKey["feast-nativity"],
  byKey["feast-circumcision-of-christ"],
  byKey["feast-theophany"],
  byKey["feast-wedding-at-cana"],
  byKey["feast-entry-of-christ-into-the-temple"],
  byKey["feast-feast-of-the-cross"],
  byKey["feast-palm-sunday"],
  byKey["feast-annunciation"],
  byKey["feast-covenant-thursday"],
  byKey["feast-feast-of-the-resurrection"],
  byKey["feast-thomas-sunday"],
  byKey["feast-ascension"],
  byKey["feast-pentecost"],
  byKey["feast-entry-of-christ-into-egypt"],
  byKey["feast-transfiguration"],
];
