#!/usr/bin/env python3
"""Extract Synaxarium day titles + story teasers into a TS module for the worker.

The worker's OG share pages (/synax/MM-DD) need the day's real title and a
short teaser of the story, but the worker can't read the static JSON assets at
runtime — so we bake titles + teasers in at build time. Re-run this script
whenever public/synaxarium/*.json change, then rebuild + push.

Usage: python3 scripts/extract_synax_titles.py
"""
import glob
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, 'src', 'synaxTitles.ts')
TEASER_LEN = 200


import re

PUNCT = '،,.:؛;!؟?—–-()«»"\' '


def norm(s):
    s = re.sub(r'[،,.:؛;!؟?—–\-()«»"\'“”]', '', s)
    return re.sub(r'\s+', ' ', s).strip()


def teaser(body, titles):
    """First story paragraph (skipping title paragraphs), ~200 chars."""
    if not body:
        return ''
    title_set = {norm(t) for t in titles if norm(t)}
    paras = [p.strip() for p in body.replace('\r', '').split('\n\n')]
    story = ''
    for p in paras:
        np = norm(p)
        if not np:
            continue
        # skip paragraphs that are (a prefix of) a known title
        if any(np == t or np.startswith(t) or t.startswith(np) for t in title_set):
            continue
        story = p
        break
    if not story:
        story = next((p for p in paras if norm(p)), '')
    story = ' '.join(story.split())
    if len(story) > TEASER_LEN:
        cut = story[:TEASER_LEN].rsplit(' ', 1)[0]
        story = (cut or story[:TEASER_LEN]) + '…'
    return story


days = {}
for path in sorted(glob.glob(os.path.join(REPO, 'public', 'synaxarium', '*.json'))):
    mm = os.path.basename(path).split('.')[0]
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    for day, entry in data.items():
        key = f'{mm}-{str(day).zfill(2)}'
        en = entry.get('en', []) or []
        ar = entry.get('ar', []) or []
        days[key] = {
            'en': en,
            'ar': ar,
            'teaser_en': teaser(entry.get('text', ''), en),
            'teaser_ar': teaser(entry.get('ar_text', ''), ar),
        }

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED by scripts/extract_synax_titles.py — do not edit by hand.\n')
    f.write('// Synaxarium day titles + story teasers ("MM-DD" -> data), baked in so the\n')
    f.write('// worker can render OG share pages with the real title and a story hook.\n')
    f.write('export interface SynaxDayShare { en: string[]; ar: string[]; teaser_en: string; teaser_ar: string }\n')
    f.write('export const SYNAX_TITLES: Record<string, SynaxDayShare> = ')
    json.dump(days, f, ensure_ascii=False)
    f.write(';\n')

size = os.path.getsize(OUT)
missing = [k for k, v in days.items() if not (v['teaser_ar'] or v['teaser_en'])]
print(f'wrote {OUT} ({len(days)} days, {size} bytes, {len(missing)} without teaser)')
