#!/usr/bin/env python3
"""Extract Synaxarium day titles (no body text) into a TS module for the worker.

The worker's OG share pages (/synax/MM-DD) need the day's real titles, but the
worker can't read the static JSON assets at runtime — so we bake the titles in
at build time. Re-run this script whenever the titles in public/synaxarium/
change, then rebuild + push.

Usage: python3 scripts/extract_synax_titles.py
"""
import glob
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, 'src', 'synaxTitles.ts')

titles = {}
for path in sorted(glob.glob(os.path.join(REPO, 'public', 'synaxarium', '*.json'))):
    mm = os.path.basename(path).split('.')[0]
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    for day, entry in data.items():
        key = f'{mm}-{str(day).zfill(2)}'
        titles[key] = {
            'en': entry.get('en', []) or [],
            'ar': entry.get('ar', []) or [],
        }

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED by scripts/extract_synax_titles.py — do not edit by hand.\n')
    f.write('// Synaxarium day titles only ("MM-DD" -> titles), baked in so the\n')
    f.write('// worker can render OG share pages with the real day title.\n')
    f.write('export const SYNAX_TITLES: Record<string, { en: string[]; ar: string[] }> = ')
    json.dump(titles, f, ensure_ascii=False)
    f.write(';\n')

size = os.path.getsize(OUT)
print(f'wrote {OUT} ({len(titles)} days, {size} bytes)')
