import React, { createContext, useContext, useState, useEffect } from 'react';
import { ThemeMode, Language } from '../types';

interface ThemeContextType {
  theme: ThemeMode;
  setTheme: (mode: ThemeMode) => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'OrthodoxConnect',
    tagline: 'Orthodox Fellowship & Community Network',
    feed: 'Feed',
    videos: 'Videos',
    reels: 'Videos',
    goLive: 'Go Live',
    myNetwork: 'My Network',
    messages: 'Messages',
    calendar: 'Calendar',
    adminPanel: 'Admin Panel',
    profile: 'Profile',
    notifications: 'Notifications',
    inviteFriends: 'Invite Friends',
    searchParish: 'Search posts, saints, or parishes...',
    dailyCommemoration: 'Daily Commemoration',
    dailyScripture: 'Daily Scripture',
    fastingSeason: 'Fasting Season',
    sharePost: 'Share something with your parish fellowship...',
    post: 'Post',
    like: 'Blessing / Like',
    comment: 'Comment',
    reshare: 'Reshare',
    quote: 'Quote',
    activeChats: 'Active Chats',
    onlineNow: 'Online Now',
    editProfile: 'Edit Profile',
    signOut: 'Sign Out',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    copyLink: 'Copy Link',
    shareWhatsApp: 'Share via WhatsApp',
    referralLink: 'Referral Invite Link',
    scanQr: 'Scan QR Code to Join OrthodoxConnect',
    language: 'Language',
    themeMode: 'Theme Mode',
    ancientGold: 'Ancient Gold',
    dark: 'Dark',
    light: 'Light',
    arabic: 'العربية',
    english: 'English',
    users: 'Registered Users',
    activeSessions: 'Active Sessions',
    userDirectory: 'User Directory',
    promoteAdmin: 'Promote to Admin',
    demoteUser: 'Demote to User',
    role: 'Role',
    parish: 'Parish / Monastery',
    bio: 'Biography',
    fullName: 'Full Name',
    password: 'New Password',
    updateProfile: 'Update Profile',
    liveStreams: 'Parish Live Streams',
    joinRoom: 'Join Room',
    activeMembers: 'active members',
    blessingRequest: 'Ask for Priest Blessing',
    send: 'Send',
    typeMessage: 'Write a message...',
    allParishFeed: 'All Parish Feed',
    followingFeed: 'Following Feed',
    peopleIFollow: 'People I Follow',
    myJoinedGroups: 'My Joined Groups',
    discoverCommunity: 'Discover Community',
    parishEventsTitle: 'Parish Events & Liturgical Calendar',
    parishEventsSub: 'Divine Liturgies, Feasts, Bible Studies, Pilgrimages, and Community Gatherings',
    createParishEvent: 'Create Parish Event',
    parishEventsTab: 'Parish Events',
    orthodoxFeastsTab: 'Orthodox Feasts & Fasting Rule',
    todaysCommemoration: "TODAY'S COMMEMORATION",
    upcomingGreatFeasts: 'Upcoming Great Feasts & Fasting Rule',
    enterRoom: 'Enter Room',
    joinGroup: 'Join Group',
    joined: 'Joined',
    leaveGroup: 'Leave',
    follow: 'Follow',
    following: 'Following',
    unfollow: 'Unfollow',
    host: 'Host',
    shareStory: 'Share Story',
    parishStory: 'Parish Story',
    uploadReel: 'Upload Reel',
    startStream: 'Start Stream',
    markAllRead: 'Mark All as Read',
    clearAll: 'Clear All',
    noNotifications: 'No notifications yet',
    referralSub: 'Share parish referral link & QR code with your community.',
    saintOfTheDay: 'Saint of the Day',
    audioCall: 'Audio Call',
    videoCall: 'Video Call',
    calling: 'Calling...',
    incomingCall: 'Incoming Call',
    inCall: 'Active Call',
    muteMic: 'Mute Mic',
    unmuteMic: 'Unmute Mic',
    cameraOff: 'Camera Off',
    cameraOn: 'Camera On',
    endCall: 'End Call',
    voiceNote: 'Voice Note',
    recordingVoiceNote: 'Recording voice note...',
    attachImage: 'Attach Photo',
    attachVideo: 'Attach Video',
    recordAudio: 'Record Audio',
    createCustomGroup: 'Create New Group',
    groupName: 'Group Name',
    groupType: 'Group Category',
    groupDescription: 'Group Description',
    groupIcon: 'Group Icon Symbol',
    startGroupCall: 'Start Group Audio/Video Call',
    groupCallActive: 'Group Call in Progress',
    leaveCall: 'Leave Call',
    participants: 'Participants',
    manageGroupAdmins: 'Manage Group Admins',
    inviteToGroup: 'Invite Members to Group',
    liveParishBroadcasts: 'Live Parish Broadcasts',
    liveParishBroadcastsSub: 'Watch Divine Liturgy and Church Services live via Device Camera or Bunny Stream',
    startLiveBroadcast: 'Start Live Broadcast',
    youAreBroadcasting: 'You Are Currently Broadcasting Live',
    broadcastingSub: 'Device camera and microphone are live and streaming to parishioners.',
    endBroadcastNow: 'End Broadcast Now',
    liveParishBadge: 'LIVE PARISH BROADCAST',
    watchingCount: 'Watching',
    celebrant: 'Celebrant',
    lightCandle: 'Light Candle',
    candleLitNotice: 'Candle lit in prayer and blessing!',
    shareStream: 'Share',
    broadcastInfo: 'Broadcast Information',
    broadcastInfoSub: 'Streamed directly from parish. All faithful are invited to unite in prayer during divine services.',
    moreParishBroadcasts: 'More Parish Broadcasts',
    parishLiveChat: 'Parish Live Chat',
    liveFeed: 'LIVE FEED',
    requestBlessing: 'Request Blessing',
    blessingRequested: '✓ Blessing Requested',
    askForPriestBlessing: 'Ask for priest blessing during divine service',
    chatWithParish: 'Chat with parishioners...',
    clergy: 'CLERGY',
    lordHaveMercy: '🙏 Lord Have Mercy',
    amen: '☦️ Amen',
    lightCandleReaction: '🕯️ Light a Candle',
    requestBlessingReaction: '✝️ Request Blessing',
    launchWebcamStream: 'Launch Device Webcam Stream',
    noStreamAttached: 'No external Bunny stream link attached. Click below to launch your device camera and stream live directly to your parish.',
    unmuteStream: 'Unmute Live Stream',
    liveCameraAndMic: '🔴 Live Device Camera & Microphone',
    parishServiceBroadcast: 'Parish Divine Service Broadcast',
    bless: 'Bless',
    blessed: 'Blessed',
    youBlessed: 'You blessed this reflection',
    youAnd: 'You and',
    others: 'others',
    peopleWhoBlessed: 'People who blessed this reflection',
    writeAComment: 'Write a reflection or comment...',
    noReflectionsYet: 'No reflections shared yet. Be the first to share your thoughts!',
    delete: 'Delete',
    report: 'Report',
    reshareToFeed: 'Reshare to Feed',
    copyLinkToPost: 'Copy link to post',
    forYou: 'For You',
    trending: 'Trending',
    allPosts: 'All Posts',
    followingOnly: 'Following Only',
    uploadVideo: 'Upload Video',
    uploadCaptionPlaceholder: 'Write a caption or hashtags for your video...',
    selectVideoFile: 'Select Video File',
    dragDropVideo: 'Drag and drop video here or click to select',
    uploadingVideo: 'Uploading and processing video...',
    publishVideo: 'Publish Video',
    cancel: 'Cancel',
    whatsOnYourMind: "What's on your mind?",
    createPost: 'Create Post',
    photoVideo: 'Photo / Video',
    audioReflection: 'Audio Reflection',
    parishTag: 'Parish Tag',
    scriptureTag: 'Scripture Tag',
    greatFeasts: 'Great Feasts',
    fastingRule: 'Fasting Rule',
    allCategories: 'All Categories',
    divineLiturgy: 'Divine Liturgy',
    vespers: 'Vespers',
    bibleStudy: 'Bible Study',
    youthMeeting: 'Youth Meeting',
    pilgrimage: 'Pilgrimage',
    parishFestival: 'Parish Festival',
    fellowshipRooms: 'Fellowship Rooms',
    activeVoiceRooms: 'Active Voice & Video Rooms',
    createRoom: 'Create New Room',
    membersInRoom: 'members in room',
    parishMonasteries: 'Parishes & Monasteries',
    searchConversations: 'Search conversations...',
    noMessagesYet: 'No messages yet',
    startConversation: 'Start a conversation with fellow parishioners',
    myProfile: 'My Profile',
    followers: 'Followers',
    postsCount: 'Posts',
    saveChanges: 'Save Changes',
  },
  ar: {
    appName: 'أورثوذكس كونكت',
    tagline: 'شبكة التواصل والأخوة الأرثوذكسية',
    feed: 'المنشورات',
    videos: 'الفيديوهات',
    reels: 'الفيديوهات',
    goLive: 'بث مباشر',
    myNetwork: 'شبكتي وغرف الأخوة',
    messages: 'الرسائل',
    calendar: 'التقويم الكنسي',
    adminPanel: 'لوحة الإدارة',
    profile: 'الملف الشخصي',
    notifications: 'الإشعارات',
    inviteFriends: 'دعوة الأصدقاء',
    searchParish: 'ابحث في المنشورات، القديسين، أو الرعايا...',
    dailyCommemoration: 'تذكار القديسين اليومي',
    dailyScripture: 'القراءة اليومية',
    fastingSeason: 'فترة الصوم',
    sharePost: 'شارك تأملاً أو خبراً مع رعيتك...',
    post: 'نشر',
    like: 'بركة / إعجاب',
    comment: 'تعليق',
    reshare: 'إعادة مشاركة',
    quote: 'اقتباس',
    activeChats: 'المحادثات النشطة',
    onlineNow: 'متصل الآن',
    editProfile: 'تعديل الملف الشخصي',
    signOut: 'تسجيل الخروج',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    copyLink: 'نسخ الرابط',
    shareWhatsApp: 'مشاركة عبر واتساب',
    referralLink: 'رابط الدعوة الخاص بك',
    scanQr: 'امسح رمز QR للانضمام إلى أورثوذكس كونكت',
    language: 'اللغة',
    themeMode: 'المظهر',
    ancientGold: 'النمط الذهبي القديم',
    dark: 'الداكن',
    light: 'الفياتح',
    arabic: 'العربية',
    english: 'English',
    users: 'المستخدمون المسجلون',
    activeSessions: 'الجلسات النشطة',
    userDirectory: 'دليل الأعضاء',
    promoteAdmin: 'ترقية إلى مسؤول',
    demoteUser: 'تنزيل إلى مستخدم',
    role: 'الرتبة',
    parish: 'الرعية / الدير',
    bio: 'السيرة الذاتية',
    fullName: 'الاسم الكامل',
    password: 'كلمة المرور الجديدة',
    updateProfile: 'حفظ التغييرات',
    liveStreams: 'البث المباشر للرعايا',
    joinRoom: 'الانضمام إلى الغرفة',
    activeMembers: 'أعضاء متصلين',
    blessingRequest: 'طلب بركة الكاهن',
    send: 'إرسال',
    typeMessage: 'اكتب رسالة...',
    allParishFeed: 'منشورات الرعية العامة',
    followingFeed: 'منشورات المتابَعين',
    peopleIFollow: 'الأعضاء المتابَعون',
    myJoinedGroups: 'المجموعات المنضم إليها',
    discoverCommunity: 'استكشاف المجتمع',
    parishEventsTitle: 'فعاليات الكنيسة والتقويم اللتيرجي',
    parishEventsSub: 'القداسات الإلهية، الأعياد، دراسات الكتاب المقدس، واللقاءات الكنسية',
    createParishEvent: 'إضافة فعالية كنسية',
    parishEventsTab: 'الفعاليات الكنسية',
    orthodoxFeastsTab: 'الأعياد الأرثوذكسية وقواعد الصوم',
    todaysCommemoration: 'تذكار اليوم الكنسي',
    upcomingGreatFeasts: 'الأعياد الكنسية القادمة وقواعد الصوم',
    enterRoom: 'دخول الغرفة',
    joinGroup: 'انضمام للمجموعة',
    joined: 'منضم',
    leaveGroup: 'مغادرة',
    follow: 'متابعة',
    following: 'مُتابَع',
    unfollow: 'إلغاء المتابعة',
    host: 'المستضيف',
    shareStory: 'إضافة قصة',
    parishStory: 'قصص الرعية',
    uploadReel: 'رفع فيديو ريلز',
    startStream: 'بدء البث المباشر',
    markAllRead: 'تحديد الكل كمقروء',
    clearAll: 'مسح الكل',
    noNotifications: 'لا توجد إشعارات حالياً',
    referralSub: 'شارك رابط الدعوة ورمز QR الخاص بالرعية مع مجتمعك.',
    saintOfTheDay: 'قديس اليوم',
    audioCall: 'مكالمة صوتية',
    videoCall: 'مكالمة فيديو',
    calling: 'جاري الاتصال...',
    incomingCall: 'مكالمة واردة',
    inCall: 'مكالمة نشطة',
    muteMic: 'كتم الصوت',
    unmuteMic: 'تشغيل الصوت',
    cameraOff: 'إيقاف الكاميرا',
    cameraOn: 'تشغيل الكاميرا',
    endCall: 'إنهاء المكالمة',
    voiceNote: 'رسالة صوتية',
    recordingVoiceNote: 'جاري تسجيل الرسالة الصوتية...',
    attachImage: 'إرفاق صورة',
    attachVideo: 'إرفاق فيديو',
    recordAudio: 'تسجيل صوتي',
    createCustomGroup: 'إنشاء مجموعة جديدة',
    groupName: 'اسم المجموعة',
    groupType: 'تصنيف المجموعة',
    groupDescription: 'وصف المجموعة',
    groupIcon: 'رمز المجموعة',
    startGroupCall: 'بدء مكالمة جماعية صوتية/فيديو',
    groupCallActive: 'مكالمة جماعية جارية',
    leaveCall: 'مغادرة المكالمة',
    participants: 'المشاركون',
    manageGroupAdmins: 'إدارة مسؤولي المجموعة',
    inviteToGroup: 'دعوة أعضاء للمجموعة',
    liveParishBroadcasts: 'البث المباشر للرعايا',
    liveParishBroadcastsSub: 'شاهد القداسات الإلهية والخدمات الكنسية مباشرة عبر كاميرا الجهاز أو خدمة البث',
    startLiveBroadcast: 'بدء بث مباشر',
    youAreBroadcasting: 'أنت تبث مباشرة الآن',
    broadcastingSub: 'كاميرا الجهاز والميكروفون في وضع البث المباشر لأبناء الرعية.',
    endBroadcastNow: 'إنهاء البث الآن',
    liveParishBadge: 'بث كنسي مباشر',
    watchingCount: 'مشاهد',
    celebrant: 'الكاهن الخادم',
    lightCandle: 'إيقاد شمعة',
    candleLitNotice: 'تم إيقاد شمعة بالصلاة والبركة!',
    shareStream: 'مشاركة',
    broadcastInfo: 'معلومات البث',
    broadcastInfoSub: 'يتم البث مباشرة من الرعية. جميع المؤمنين مدعوون للاتحاد في الصلاة خلال الخدمات الإلهية.',
    moreParishBroadcasts: 'المزيد من البث المباشر للرعايا',
    parishLiveChat: 'المحادثة المباشرة للرعية',
    liveFeed: 'بث مباشر',
    requestBlessing: 'طلب بركة',
    blessingRequested: '✓ تم طلب البركة',
    askForPriestBlessing: 'طلب بركة الكاهن خلال الخدمة الإلهية',
    chatWithParish: 'اكتب رسالة للرعية...',
    clergy: 'إكليروس',
    lordHaveMercy: '🙏 يا رب ارحم',
    amen: '☦️ آمين',
    lightCandleReaction: '🕯️ إيقاد شمعة',
    requestBlessingReaction: '✝️ طلب بركة',
    launchWebcamStream: 'تشغيل كاميرا الجهاز للبث',
    noStreamAttached: 'لا يوجد رابط بث خارجي. انقر أدناه لتشغيل كاميرا جهازك والبث مباشرة لرعيتك.',
    unmuteStream: 'تشغيل الصوت للبث',
    liveCameraAndMic: '🔴 كاميرا وميكروفون الجهاز قيد البث المباشر',
    parishServiceBroadcast: 'بث الخدمة الإلهية للرعية',
    bless: 'تبارك',
    blessed: 'تباركت',
    youBlessed: 'لقد نلت بركة هذا التأمل',
    youAnd: 'أنت و',
    others: 'آخرين',
    peopleWhoBlessed: 'الذين باركوا هذا التأمل',
    writeAComment: 'اكتب تأملاً أو تعليقاً...',
    noReflectionsYet: 'لم تتم مشاركة أي تأملات بعد. كن أول من يشارك!',
    delete: 'حذف',
    report: 'إبلاغ',
    reshareToFeed: 'إعادة نشر في اليوميات',
    copyLinkToPost: 'نسخ رابط المنشور',
    forYou: 'لك',
    trending: 'الشائع',
    allPosts: 'جميع المنشورات',
    followingOnly: 'المتابعون فقط',
    uploadVideo: 'رفع فيديو',
    uploadCaptionPlaceholder: 'اكتب وصفاً أو هاشتاغ للفيديو...',
    selectVideoFile: 'اختر ملف الفيديو',
    dragDropVideo: 'اسحب وأفلت الفيديو هنا أو انقر للاختيار',
    uploadingVideo: 'جاري رفع ومعالجة الفيديو...',
    publishVideo: 'نشر الفيديو',
    cancel: 'إلغاء',
    whatsOnYourMind: 'ماذا يدور في ذهنك؟',
    createPost: 'إنشاء منشور',
    photoVideo: 'صورة / فيديو',
    audioReflection: 'تسجيل صوتي',
    parishTag: 'وسم الرعية',
    scriptureTag: 'آية كتابية',
    greatFeasts: 'الأعياد الكنسية الكبرى',
    fastingRule: 'قواعد الصوم',
    allCategories: 'جميع الفئات',
    divineLiturgy: 'القداس الإلهي',
    vespers: 'صلاة الغروب',
    bibleStudy: 'دراسة الكتاب المقدس',
    youthMeeting: 'اجتماع الشباب',
    pilgrimage: 'رحلة حج كنسية',
    parishFestival: 'مهرجان الرعية',
    fellowshipRooms: 'غرف الأخوة واللقاءات',
    activeVoiceRooms: 'غرف الصوت والفيديو النشطة',
    createRoom: 'إنشاء غرفة جديدة',
    membersInRoom: 'أعضاء في الغرفة',
    parishMonasteries: 'الأديرة والرعايا',
    searchConversations: 'البحث في المحادثات...',
    noMessagesYet: 'لا توجد رسائل بعد',
    startConversation: 'ابدأ محادثة مع أعضاء رعيتك',
    myProfile: 'ملفي الشخصي',
    followers: 'المتابعون',
    postsCount: 'المنشورات',
    saveChanges: 'حفظ التعديلات',
  },
};

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setThemeState] = useState<ThemeMode>(() => {
    return (localStorage.getItem('oc_theme') as ThemeMode) || 'ancient';
  });

  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('oc_lang') as Language) || 'en';
  });

  const setTheme = (mode: ThemeMode) => {
    setThemeState(mode);
    localStorage.setItem('oc_theme', mode);
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('oc_lang', lang);
  };

  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove('theme-dark', 'theme-light', 'theme-ancient', 'dark', 'light');
    if (theme === 'dark') {
      root.classList.add('dark', 'theme-dark');
    } else if (theme === 'ancient') {
      root.classList.add('theme-ancient');
    } else {
      root.classList.add('light', 'theme-light');
    }
  }, [theme]);

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute('lang', language);
    root.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <ThemeContext.Provider value={{ theme, setTheme, language, setLanguage, t }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};
