import React, { createContext, useContext, useState, useEffect } from 'react';
import { ThemeMode, Language } from '../types';

interface ThemeContextType {
  theme: ThemeMode;
  setTheme: (mode: ThemeMode) => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  accentColor: string;
  setAccentColor: (c: string) => void;
  t: (key: string) => string;
}

// amt -1..1: negative darkens, positive lightens a hex color
const shadeHex = (hex: string, amt: number): string => {
  const n = hex.replace('#', '');
  const full = n.length === 3 ? n.split('').map((c) => c + c).join('') : n;
  const num = parseInt(full, 16);
  let r = (num >> 16) & 255, g = (num >> 8) & 255, b = num & 255;
  if (amt >= 0) { r += (255 - r) * amt; g += (255 - g) * amt; b += (255 - b) * amt; }
  else { r *= 1 + amt; g *= 1 + amt; b *= 1 + amt; }
  const hx = (v: number) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, '0');
  return `#${hx(r)}${hx(g)}${hx(b)}`;
};

const ACCENT_VARS = ['--ac-bright', '--ac-bright-tx', '--ac-bright-dk', '--ac-gold', '--ac-gold-tx', '--ac-gold-deep', '--ac-bronze', '--ac-bronze-tx', '--ac-bronze-dk', '--bg-tabbar'];

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'OrthodoxConnect',
    tagline: 'Orthodox Fellowship & Community Network',
    feed: 'Feed',
    videos: 'Videos',
    reels: 'Videos',
    goLive: 'Go Live',
    myNetwork: 'My Network',
    messages: 'Messages',
    calendar: 'Calendar',
    adminPanel: 'Admin Panel',
    profile: 'Profile',
    notifications: 'Notifications',
    inviteFriends: 'Invite Friends',
    searchParish: 'Search posts, saints, or parishes...',
    searchPeople: 'People',
    searchPosts: 'Posts',
    searchChurches: 'Churches',
    searching: 'Searching…',
    searchNoResults: 'No results found',
    dailyCommemoration: 'Daily Commemoration',
    dailyScripture: 'Daily Scripture',
    fastingSeason: 'Fasting Season',
    sharePost: 'Share something with your parish fellowship...',
    post: 'Post',
    like: 'Blessing / Like',
    comment: 'Comment',
    reshare: 'Reshare',
    quote: 'Quote',
    activeChats: 'Active Chats',
    onlineNow: 'Online Now',
    editProfile: 'Edit Profile',
    signOut: 'Sign Out',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    copyLink: 'Copy Link',
    shareWhatsApp: 'Share via WhatsApp',
    referralLink: 'Referral Invite Link',
    scanQr: 'Scan QR Code to Join OrthodoxConnect',
    language: 'Language',
    themeMode: 'Theme Mode',
    ancientGold: 'Vintage mood',
    facebookMode: 'Skylight mood',
    dark: 'Night mood vintage',
    light: 'Daylight vintage',
    arabic: 'العربية',
    english: 'English',
    users: 'Registered Users',
    activeSessions: 'Active Sessions',
    userDirectory: 'User Directory',
    promoteAdmin: 'Promote to Admin',
    demoteUser: 'Demote to User',
    role: 'Role',
    parish: 'Your Church Name',
    bio: 'Biography',
    fullName: 'Full Name',
    password: 'New Password',
    updateProfile: 'Update Profile',
    liveStreams: 'Parish Live Streams',
    joinRoom: 'Join Room',
    activeMembers: 'active members',
    blessingRequest: 'Ask for Priest Blessing',
    send: 'Send',
    typeMessage: 'Write a message...',
    allParishFeed: 'All Parish Feed',
    followingFeed: 'Following Feed',
    peopleIFollow: 'People I Follow',
    myJoinedGroups: 'My Joined Groups',
    discoverCommunity: 'Discover Community',
    parishEventsTitle: 'Parish Events & Liturgical Calendar',
    parishEventsSub: 'Divine Liturgies, Feasts, Bible Studies, Pilgrimages, and Community Gatherings',
    createParishEvent: 'Create Parish Event',
    parishEventsTab: 'Parish Events',
    orthodoxFeastsTab: 'Orthodox Feasts & Fasting Rule',
    todaysCommemoration: "TODAY'S COMMEMORATION",
    upcomingGreatFeasts: 'Upcoming Great Feasts & Fasting Rule',
    enterRoom: 'Enter Room',
    joinGroup: 'Join Group',
    joined: 'Joined',
    leaveGroup: 'Leave',
    follow: 'Follow',
    following: 'Following',
    unfollow: 'Unfollow',
    host: 'Host',
    shareStory: 'Share Story',
    parishStory: 'Parish Story',
    uploadReel: 'Upload Reel',
    startStream: 'Start Stream',
    markAllRead: 'Mark All as Read',
    clearAll: 'Clear All',
    noNotifications: 'No notifications yet',
    referralSub: 'Share parish referral link & QR code with your community.',
    saintOfTheDay: 'Saint of the Day',
    audioCall: 'Audio Call',
    videoCall: 'Video Call',
    calling: 'Calling...',
    incomingCall: 'Incoming Call',
    inCall: 'Active Call',
    muteMic: 'Mute Mic',
    unmuteMic: 'Unmute Mic',
    cameraOff: 'Camera Off',
    cameraOn: 'Camera On',
    endCall: 'End Call',
    voiceNote: 'Voice Note',
    recordingVoiceNote: 'Recording voice note...',
    attachImage: 'Attach Photo',
    attachVideo: 'Attach Video',
    recordAudio: 'Record Audio',
    createCustomGroup: 'Create New Group',
    groupName: 'Group Name',
    groupType: 'Group Category',
    groupDescription: 'Group Description',
    groupIcon: 'Group Icon Symbol',
    startGroupCall: 'Start Group Audio/Video Call',
    groupCallActive: 'Group Call in Progress',
    leaveCall: 'Leave Call',
    participants: 'Participants',
    manageGroupAdmins: 'Manage Group Admins',
    inviteToGroup: 'Invite Members to Group',
    liveParishBroadcasts: 'Live Parish Broadcasts',
    liveParishBroadcastsSub: 'Watch Divine Liturgy and Church Services live via Device Camera or Bunny Stream',
    startLiveBroadcast: 'Start Live Broadcast',
    youAreBroadcasting: 'You Are Currently Broadcasting Live',
    broadcastingSub: 'Device camera and microphone are live and streaming to parishioners.',
    endBroadcastNow: 'End Broadcast Now',
    liveParishBadge: 'LIVE PARISH BROADCAST',
    watchingCount: 'Watching',
    celebrant: 'Celebrant',
    lightCandle: 'Light Candle',
    candleLitNotice: 'Candle lit in prayer and blessing!',
    shareStream: 'Share',
    broadcastInfo: 'Broadcast Information',
    broadcastInfoSub: 'Streamed directly from parish. All faithful are invited to unite in prayer during divine services.',
    moreParishBroadcasts: 'More Parish Broadcasts',
    parishLiveChat: 'Parish Live Chat',
    liveFeed: 'LIVE FEED',
    requestBlessing: 'Request Blessing',
    blessingRequested: '✓ Blessing Requested',
    askForPriestBlessing: 'Ask for priest blessing during divine service',
    chatWithParish: 'Chat with parishioners...',
    clergy: 'CLERGY',
    lordHaveMercy: '🙏 Lord Have Mercy',
    amen: '☦️ Amen',
    lightCandleReaction: '🕯️ Light a Candle',
    requestBlessingReaction: '✝️ Request Blessing',
    launchWebcamStream: 'Launch Device Webcam Stream',
    noStreamAttached: 'No external Bunny stream link attached. Click below to launch your device camera and stream live directly to your parish.',
    unmuteStream: 'Unmute Live Stream',
    liveCameraAndMic: '🔴 Live Device Camera & Microphone',
    parishServiceBroadcast: 'Parish Divine Service Broadcast',
    bless: 'Bless',
    blessed: 'Blessed',
    youBlessed: 'You blessed this reflection',
    youAnd: 'You and',
    others: 'others',
    peopleWhoBlessed: 'People who blessed this reflection',
    writeAComment: 'Write a reflection or comment...',
    noReflectionsYet: 'No reflections shared yet. Be the first to share your thoughts!',
    delete: 'Delete',
    report: 'Report',
    reshareToFeed: 'Reshare to Feed',
    copyLinkToPost: 'Copy link to post',
    forYou: 'For You',
    trending: 'Trending',
    allPosts: 'All Posts',
    followingOnly: 'Following Only',
    uploadVideo: 'Upload Video',
    uploadCaptionPlaceholder: 'Write a caption or hashtags for your video...',
    selectVideoFile: 'Select Video File',
    dragDropVideo: 'Drag and drop video here or click to select',
    uploadingVideo: 'Uploading and processing video...',
    publishVideo: 'Publish Video',
    cancel: 'Cancel',
    whatsOnYourMind: "What's on your mind?",
    createPost: 'Create Post',
    photoVideo: 'Photo / Video',
    audioReflection: 'Audio Reflection',
    parishTag: 'Parish Tag',
    scriptureTag: 'Scripture Tag',
    greatFeasts: 'Great Feasts',
    fastingRule: 'Fasting Rule',
    allCategories: 'All Categories',
    divineLiturgy: 'Divine Liturgy',
    vespers: 'Vespers',
    bibleStudy: 'Bible Study',
    youthMeeting: 'Youth Meeting',
    pilgrimage: 'Pilgrimage',
    parishFestival: 'Parish Festival',
    fellowshipRooms: 'Fellowship Rooms',
    activeVoiceRooms: 'Active Voice & Video Rooms',
    createRoom: 'Create New Room',
    membersInRoom: 'members in room',
    parishMonasteries: 'Parishes & Monasteries',
    searchConversations: 'Search conversations...',
    noMessagesYet: 'No messages yet',
    startConversation: 'Start a conversation with fellow parishioners',
    myProfile: 'My Profile',
    followers: 'Followers',
    postsCount: 'Posts',
    saveChanges: 'Save Changes',
    adminAccessRestricted: 'Access Restricted',
    adminAccessRestrictedMsg: 'Super Admin, Admin, or Owner privileges are required to access the Moderation & Management Panel.',
    adminPanelTitle: 'Admin & Content Moderation Panel',
    adminPanelSubtitle: 'Manage registered parishioners, assign clergy roles, review reports, and audit system activity',
    adminTotalMembers: 'Total Members',
    adminAdmins: 'Admins',
    adminClergy: 'Clergy',
    adminPendingReports: 'Pending Reports',
    adminTabUsers: 'User Directory & Roles',
    adminTabClergy: 'Clergy',
    adminTabReports: 'Content Reports Queue',
    adminTabAudit: 'Moderation Audit Log',
    adminUserDirTitle: 'Parish User Directory & Management',
    adminClergyDirTitle: 'Clergy Directory',
    adminAddMember: 'Add Member',
    adminSearchMembers: 'Search members by name, email, or parish...',
    adminThMember: 'Member',
    adminThEmail: 'Email',
    adminThParish: 'Parish',
    adminThRole: 'Role',
    adminThJoined: 'Joined Date',
    adminThStatus: 'Status',
    adminThActions: 'Actions',
    adminNoMatch: 'No registered parishioners match your search query.',
    adminNoClergy: 'No clergy members found.',
    adminNew: 'New',
    adminSuperAdmin: 'SUPER ADMIN',
    adminAdminRole: 'ADMIN',
    adminRoleMember: 'Member',
    adminRoleClergy: 'Clergy',
    adminRoleAdmin: 'Admin',
    adminBanned: 'Banned',
    adminWarnings: 'Warnings',
    adminGoodStanding: 'Good Standing',
    adminSuperAdminProtected: 'Super Admin (Protected)',
    adminBan: 'Ban',
    adminUnban: 'Unban',
    adminDeleteUser: 'Delete User',
    adminDeleteUserTitle: 'Remove / Delete User',
    adminAdminProtected: 'Admin (Protected)',
    adminAdminProtectedTip: 'Admin accounts can only be deleted by the Super Admin (orthodoxconnect.live@gmail.com)',
    adminActive: 'Active',
    adminReportsTitle: 'Reported Content Review Queue',
    adminNoFlagged: 'No flagged content. Community feed is clean!',
    adminReason: 'Reason',
    adminReportedBy: 'Reported by',
    adminReporterNote: 'Reporter Note:',
    adminAuthor: 'Author:',
    adminUnknownUser: 'Unknown User',
    adminDismiss: 'Dismiss',
    adminRemoveContent: 'Remove Content',
    adminWarnUser: 'Warn User',
    adminStatus: 'Status:',
    adminAuditTitle: 'Moderation Audit Trail Log',
    adminNoLogs: 'No moderation logs recorded yet.',
    adminPerformed: 'performed',
    adminAddMemberTitle: 'Add New Parish Member',
    adminFullName: 'Full Name *',
    adminFullNamePh: 'e.g. Deacon Nicholas',
    adminEmailAddress: 'Email Address *',
    adminEmailPh: 'e.g. nicholas@orthodoxparish.org',
    adminParishLabel: 'Parish / Monastery',
    adminParishPh: 'e.g. St. George Cathedral',
    adminInitialRole: 'Initial Role',
    adminCancel: 'Cancel',
    adminCreateMember: 'Create Member',
    adminConfirmDelete: 'Confirm User Deletion',
    adminConfirmDeleteMsg: 'This action will remove the member profile from the parish network.',
    adminName: 'Name:',
    adminEmail: 'Email:',
    adminParish: 'Parish:',
    adminRemoveMember: 'Remove Member',
    adminRoleUpdated: 'User role updated to {role}',
    adminRoleUpdatedLocal: 'Role updated locally to {role}',
    adminRemoved: 'Removed {name} from parish directory.',
    adminAdded: 'Added {name} to parish directory.',
    adminNeedNameEmail: 'Please provide full name and email address.',
    adminDeleteDenied: 'Permission Denied: Only the Super Admin (orthodoxconnect.live@gmail.com) can delete Admin accounts.',
    adminDeleteFailed: 'Failed to delete user account.',
    adminError: 'Error',
    colorsMode: 'My Colors',
    chooseColor: 'Choose your color',
    adminChurchImportTitle: 'US Coptic Churches',
    adminChurchImportDesc: 'Import the full directory of Coptic Orthodox churches in the USA with one tap. Existing churches are skipped.',
    adminChurchImportBtn: 'Import Churches',
    adminChurchImporting: 'Importing\u2026',
    adminChurchImportDone: 'Imported',
  },
  ar: {
    appName: 'أرثوذكسى',
    tagline: 'شبكة التواصل والأخوة الأرثوذكسية',
    feed: 'المنشورات',
    videos: 'الفيديوهات',
    reels: 'الفيديوهات',
    goLive: 'بث مباشر',
    myNetwork: 'شبكتي وغرف الأخوة',
    messages: 'الرسائل',
    calendar: 'التقويم الكنسي',
    adminPanel: 'لوحة الإدارة',
    profile: 'الملف الشخصي',
    notifications: 'الإشعارات',
    inviteFriends: 'دعوة الأصدقاء',
    searchParish: 'ابحث في المنشورات، القديسين، أو الرعايا...',
    searchPeople: 'الأشخاص',
    searchPosts: 'المنشورات',
    searchChurches: 'الكنائس',
    searching: 'جارٍ البحث…',
    searchNoResults: 'لا توجد نتائج',
    dailyCommemoration: 'تذكار القديسين اليومي',
    dailyScripture: 'القراءة اليومية',
    fastingSeason: 'فترة الصوم',
    sharePost: 'شارك تأملاً أو خبراً مع رعيتك...',
    post: 'نشر',
    like: 'بركة / إعجاب',
    comment: 'تعليق',
    reshare: 'إعادة مشاركة',
    quote: 'اقتباس',
    activeChats: 'المحادثات النشطة',
    onlineNow: 'متصل الآن',
    editProfile: 'تعديل الملف الشخصي',
    signOut: 'تسجيل الخروج',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    copyLink: 'نسخ الرابط',
    shareWhatsApp: 'مشاركة عبر واتساب',
    referralLink: 'رابط الدعوة الخاص بك',
    scanQr: 'امسح رمز QR للانضمام إلى أورثوذكس كونكت',
    language: 'اللغة',
    themeMode: 'المظهر',
    ancientGold: 'مود قديم',
    facebookMode: 'مود السماء',
    dark: 'قديم ليلي',
    light: 'قديم نهاري',
    arabic: 'العربية',
    english: 'English',
    users: 'المستخدمون المسجلون',
    activeSessions: 'الجلسات النشطة',
    userDirectory: 'دليل الأعضاء',
    promoteAdmin: 'ترقية إلى مسؤول',
    demoteUser: 'تنزيل إلى مستخدم',
    role: 'الرتبة',
    parish: 'إسم كنيستك',
    bio: 'السيرة الذاتية',
    fullName: 'الاسم الكامل',
    password: 'كلمة المرور الجديدة',
    updateProfile: 'حفظ التغييرات',
    liveStreams: 'البث المباشر للرعايا',
    joinRoom: 'الانضمام إلى الغرفة',
    activeMembers: 'أعضاء متصلين',
    blessingRequest: 'طلب بركة الكاهن',
    send: 'إرسال',
    typeMessage: 'اكتب رسالة...',
    allParishFeed: 'منشورات الرعية العامة',
    followingFeed: 'منشورات المتابَعين',
    peopleIFollow: 'الأعضاء المتابَعون',
    myJoinedGroups: 'المجموعات المنضم إليها',
    discoverCommunity: 'استكشاف المجتمع',
    parishEventsTitle: 'فعاليات الكنيسة والتقويم اللتيرجي',
    parishEventsSub: 'القداسات الإلهية، الأعياد، دراسات الكتاب المقدس، واللقاءات الكنسية',
    createParishEvent: 'إضافة فعالية كنسية',
    parishEventsTab: 'الفعاليات الكنسية',
    orthodoxFeastsTab: 'الأعياد الأرثوذكسية وقواعد الصوم',
    todaysCommemoration: 'تذكار اليوم الكنسي',
    upcomingGreatFeasts: 'الأعياد الكنسية القادمة وقواعد الصوم',
    enterRoom: 'دخول الغرفة',
    joinGroup: 'انضمام للمجموعة',
    joined: 'منضم',
    leaveGroup: 'مغادرة',
    follow: 'متابعة',
    following: 'مُتابَع',
    unfollow: 'إلغاء المتابعة',
    host: 'المستضيف',
    shareStory: 'إضافة قصة',
    parishStory: 'قصص الرعية',
    uploadReel: 'رفع فيديو ريلز',
    startStream: 'بدء البث المباشر',
    markAllRead: 'تحديد الكل كمقروء',
    clearAll: 'مسح الكل',
    noNotifications: 'لا توجد إشعارات حالياً',
    referralSub: 'شارك رابط الدعوة ورمز QR الخاص بالرعية مع مجتمعك.',
    saintOfTheDay: 'قديس اليوم',
    audioCall: 'مكالمة صوتية',
    videoCall: 'مكالمة فيديو',
    calling: 'جاري الاتصال...',
    incomingCall: 'مكالمة واردة',
    inCall: 'مكالمة نشطة',
    muteMic: 'كتم الصوت',
    unmuteMic: 'تشغيل الصوت',
    cameraOff: 'إيقاف الكاميرا',
    cameraOn: 'تشغيل الكاميرا',
    endCall: 'إنهاء المكالمة',
    voiceNote: 'رسالة صوتية',
    recordingVoiceNote: 'جاري تسجيل الرسالة الصوتية...',
    attachImage: 'إرفاق صورة',
    attachVideo: 'إرفاق فيديو',
    recordAudio: 'تسجيل صوتي',
    createCustomGroup: 'إنشاء مجموعة جديدة',
    groupName: 'اسم المجموعة',
    groupType: 'تصنيف المجموعة',
    groupDescription: 'وصف المجموعة',
    groupIcon: 'رمز المجموعة',
    startGroupCall: 'بدء مكالمة جماعية صوتية/فيديو',
    groupCallActive: 'مكالمة جماعية جارية',
    leaveCall: 'مغادرة المكالمة',
    participants: 'المشاركون',
    manageGroupAdmins: 'إدارة مسؤولي المجموعة',
    inviteToGroup: 'دعوة أعضاء للمجموعة',
    liveParishBroadcasts: 'البث المباشر للرعايا',
    liveParishBroadcastsSub: 'شاهد القداسات الإلهية والخدمات الكنسية مباشرة عبر كاميرا الجهاز أو خدمة البث',
    startLiveBroadcast: 'بدء بث مباشر',
    youAreBroadcasting: 'أنت تبث مباشرة الآن',
    broadcastingSub: 'كاميرا الجهاز والميكروفون في وضع البث المباشر لأبناء الرعية.',
    endBroadcastNow: 'إنهاء البث الآن',
    liveParishBadge: 'بث كنسي مباشر',
    watchingCount: 'مشاهد',
    celebrant: 'الكاهن الخادم',
    lightCandle: 'إيقاد شمعة',
    candleLitNotice: 'تم إيقاد شمعة بالصلاة والبركة!',
    shareStream: 'مشاركة',
    broadcastInfo: 'معلومات البث',
    broadcastInfoSub: 'يتم البث مباشرة من الرعية. جميع المؤمنين مدعوون للاتحاد في الصلاة خلال الخدمات الإلهية.',
    moreParishBroadcasts: 'المزيد من البث المباشر للرعايا',
    parishLiveChat: 'المحادثة المباشرة للرعية',
    liveFeed: 'بث مباشر',
    requestBlessing: 'طلب بركة',
    blessingRequested: '✓ تم طلب البركة',
    askForPriestBlessing: 'طلب بركة الكاهن خلال الخدمة الإلهية',
    chatWithParish: 'اكتب رسالة للرعية...',
    clergy: 'إكليروس',
    lordHaveMercy: '🙏 يا رب ارحم',
    amen: '☦️ آمين',
    lightCandleReaction: '🕯️ إيقاد شمعة',
    requestBlessingReaction: '✝️ طلب بركة',
    launchWebcamStream: 'تشغيل كاميرا الجهاز للبث',
    noStreamAttached: 'لا يوجد رابط بث خارجي. انقر أدناه لتشغيل كاميرا جهازك والبث مباشرة لرعيتك.',
    unmuteStream: 'تشغيل الصوت للبث',
    liveCameraAndMic: '🔴 كاميرا وميكروفون الجهاز قيد البث المباشر',
    parishServiceBroadcast: 'بث الخدمة الإلهية للرعية',
    bless: 'تبارك',
    blessed: 'تباركت',
    youBlessed: 'لقد نلت بركة هذا التأمل',
    youAnd: 'أنت و',
    others: 'آخرين',
    peopleWhoBlessed: 'الذين باركوا هذا التأمل',
    writeAComment: 'اكتب تأملاً أو تعليقاً...',
    noReflectionsYet: 'لم تتم مشاركة أي تأملات بعد. كن أول من يشارك!',
    delete: 'حذف',
    report: 'إبلاغ',
    reshareToFeed: 'إعادة نشر في اليوميات',
    copyLinkToPost: 'نسخ رابط المنشور',
    forYou: 'لك',
    trending: 'الشائع',
    allPosts: 'جميع المنشورات',
    followingOnly: 'المتابعون فقط',
    uploadVideo: 'رفع فيديو',
    uploadCaptionPlaceholder: 'اكتب وصفاً أو هاشتاغ للفيديو...',
    selectVideoFile: 'اختر ملف الفيديو',
    dragDropVideo: 'اسحب وأفلت الفيديو هنا أو انقر للاختيار',
    uploadingVideo: 'جاري رفع ومعالجة الفيديو...',
    publishVideo: 'نشر الفيديو',
    cancel: 'إلغاء',
    whatsOnYourMind: 'ماذا يدور في ذهنك؟',
    createPost: 'إنشاء منشور',
    photoVideo: 'صورة / فيديو',
    audioReflection: 'تسجيل صوتي',
    parishTag: 'وسم الرعية',
    scriptureTag: 'آية كتابية',
    greatFeasts: 'الأعياد الكنسية الكبرى',
    fastingRule: 'قواعد الصوم',
    allCategories: 'جميع الفئات',
    divineLiturgy: 'القداس الإلهي',
    vespers: 'صلاة الغروب',
    bibleStudy: 'دراسة الكتاب المقدس',
    youthMeeting: 'اجتماع الشباب',
    pilgrimage: 'رحلة حج كنسية',
    parishFestival: 'مهرجان الرعية',
    fellowshipRooms: 'غرف الأخوة واللقاءات',
    activeVoiceRooms: 'غرف الصوت والفيديو النشطة',
    createRoom: 'إنشاء غرفة جديدة',
    membersInRoom: 'أعضاء في الغرفة',
    parishMonasteries: 'الأديرة والرعايا',
    searchConversations: 'البحث في المحادثات...',
    noMessagesYet: 'لا توجد رسائل بعد',
    startConversation: 'ابدأ محادثة مع أعضاء رعيتك',
    myProfile: 'ملفي الشخصي',
    followers: 'المتابعون',
    postsCount: 'المنشورات',
    adminAccessRestricted: 'الدخول مقيد',
    adminAccessRestrictedMsg: 'تحتاج إلى صلاحيات المشرف العام أو المشرف أو المالك للوصول إلى لوحة الإدارة والمراجعة.',
    adminPanelTitle: 'لوحة الإدارة ومراجعة المحتوى',
    adminPanelSubtitle: 'إدارة أعضاء الرعية المسجلين، وتعيين أدوار الكهنة، ومراجعة البلاغات، وتدقيق نشاط النظام',
    adminTotalMembers: 'إجمالي الأعضاء',
    adminAdmins: 'المشرفون',
    adminClergy: 'الكهنة',
    adminPendingReports: 'البلاغات المعلقة',
    adminTabUsers: 'دليل المستخدمين والأدوار',
    adminTabClergy: 'الكهنة',
    adminTabReports: 'قائمة بلاغات المحتوى',
    adminTabAudit: 'سجل تدقيق الإدارة',
    adminUserDirTitle: 'دليل مستخدمي الرعية والإدارة',
    adminClergyDirTitle: 'دليل الكهنة',
    adminAddMember: 'إضافة عضو',
    adminSearchMembers: 'ابحث عن الأعضاء بالاسم أو البريد الإلكتروني أو الرعية...',
    adminThMember: 'العضو',
    adminThEmail: 'البريد الإلكتروني',
    adminThParish: 'الرعية',
    adminThRole: 'الدور',
    adminThJoined: 'تاريخ الانضمام',
    adminThStatus: 'الحالة',
    adminThActions: 'إجراءات',
    adminNoMatch: 'لا يوجد أعضاء مسجلون يطابقون بحثك.',
    adminNoClergy: 'لا يوجد كهنة مسجلون.',
    adminNew: 'جديد',
    adminSuperAdmin: 'مشرف عام',
    adminAdminRole: 'مشرف',
    adminRoleMember: 'عضو',
    adminRoleClergy: 'كاهن',
    adminRoleAdmin: 'مشرف',
    adminBanned: 'محظور',
    adminWarnings: 'تحذيرات',
    adminGoodStanding: 'بحالة جيدة',
    adminSuperAdminProtected: 'مشرف عام (محمي)',
    adminBan: 'حظر',
    adminUnban: 'إلغاء الحظر',
    adminDeleteUser: 'حذف المستخدم',
    adminDeleteUserTitle: 'إزالة / حذف المستخدم',
    adminAdminProtected: 'مشرف (محمي)',
    adminAdminProtectedTip: 'فقط المشرف العام (orthodoxconnect.live@gmail.com) يمكنه حذف حسابات المشرفين',
    adminActive: 'نشط',
    adminReportsTitle: 'قائمة مراجعة المحتوى المبلغ عنه',
    adminNoFlagged: 'لا يوجد محتوى مبلغ عنه. المجتمع نظيف!',
    adminReason: 'السبب',
    adminReportedBy: 'أبلغ عنه',
    adminReporterNote: 'ملاحظة المبلغ:',
    adminAuthor: 'الكاتب:',
    adminUnknownUser: 'مستخدم غير معروف',
    adminDismiss: 'تجاهل',
    adminRemoveContent: 'إزالة المحتوى',
    adminWarnUser: 'تحذير المستخدم',
    adminStatus: 'الحالة:',
    adminAuditTitle: 'سجل تدقيق الإدارة',
    adminNoLogs: 'لا توجد سجلات تدقيق مسجلة بعد.',
    adminPerformed: 'قام بـ',
    adminAddMemberTitle: 'إضافة عضو رعية جديد',
    adminFullName: 'الاسم الكامل *',
    adminFullNamePh: 'مثال: الشماس نقولا',
    adminEmailAddress: 'البريد الإلكتروني *',
    adminEmailPh: 'مثال: nicholas@orthodoxparish.org',
    adminParishLabel: 'الرعية / الدير',
    adminParishPh: 'مثال: كاتدرائية القديس جرجس',
    adminInitialRole: 'الدور الأولي',
    adminCancel: 'إلغاء',
    adminCreateMember: 'إنشاء العضو',
    adminConfirmDelete: 'تأكيد حذف المستخدم',
    adminConfirmDeleteMsg: 'سيؤدي هذا الإجراء إلى إزالة ملف العضو من شبكة الرعية.',
    adminName: 'الاسم:',
    adminEmail: 'البريد:',
    adminParish: 'الرعية:',
    adminRemoveMember: 'إزالة العضو',
    adminRoleUpdated: 'تم تحديث دور المستخدم إلى {role}',
    adminRoleUpdatedLocal: 'تم تحديث الدور محليًا إلى {role}',
    adminRemoved: 'تمت إزالة {name} من دليل الرعية.',
    adminAdded: 'تمت إضافة {name} إلى دليل الرعية.',
    adminNeedNameEmail: 'يرجى إدخال الاسم الكامل والبريد الإلكتروني.',
    adminDeleteDenied: 'مرفوض: فقط المشرف العام (orthodoxconnect.live@gmail.com) يمكنه حذف حسابات المشرفين.',
    adminDeleteFailed: 'فشل حذف حساب المستخدم.',
    adminError: 'خطأ',
    saveChanges: 'حفظ التعديلات',
    colorsMode: 'ألواني',
    chooseColor: 'اختر لونك',
    adminChurchImportTitle: 'الكنائس القبطية الأمريكية',
    adminChurchImportDesc: 'استيراد دليل الكنائس القبطية الأرثوذكسية في أمريكا بضغطة واحدة. الكنائس الموجودة لن تتكرر.',
    adminChurchImportBtn: 'استيراد الكنائس',
    adminChurchImporting: 'جارٍ الاستيراد\u2026',
    adminChurchImportDone: 'تم الاستيراد',
  },
};

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setThemeState] = useState<ThemeMode>(() => {
    return (localStorage.getItem('oc_theme') as ThemeMode) || 'facebook';
  });

  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('oc_lang') as Language;
    if (saved) return saved;
    // First launch: match the device language so Arabic users get Arabic immediately
    try {
      const nav = (navigator.language || (navigator as any).userLanguage || 'en').toLowerCase();
      if (nav.startsWith('ar')) {
        localStorage.setItem('oc_lang', 'ar');
        return 'ar';
      }
    } catch {}
    return 'en';
  });

  const setTheme = (mode: ThemeMode) => {
    setThemeState(mode);
    localStorage.setItem('oc_theme', mode);
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('oc_lang', lang);
  };

  const [accentColor, setAccentColorState] = useState<string>(() => {
    try { return localStorage.getItem('oc_accent_color') || '#1877F2'; } catch { return '#1877F2'; }
  });

  const setAccentColor = (c: string) => {
    setAccentColorState(c);
    try { localStorage.setItem('oc_accent_color', c); } catch {}
  };

  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove('theme-dark', 'theme-light', 'theme-ancient', 'theme-facebook', 'theme-colors', 'dark', 'light');
    ACCENT_VARS.forEach((v) => root.style.removeProperty(v));
    if (theme === 'dark') {
      root.classList.add('dark', 'theme-dark');
    } else if (theme === 'ancient') {
      root.classList.add('theme-ancient');
    } else if ((theme as string) === 'colors') {
      root.classList.add('light', 'theme-facebook', 'theme-colors');
      const c = accentColor;
      const set = (k: string, v: string) => root.style.setProperty(k, v);
      set('--ac-bright', c);
      set('--ac-bright-tx', c);
      set('--ac-bright-dk', shadeHex(c, -0.2));
      set('--ac-gold', c);
      set('--ac-gold-tx', c);
      set('--ac-gold-deep', shadeHex(c, -0.25));
      set('--ac-bronze', shadeHex(c, -0.08));
      set('--ac-bronze-tx', shadeHex(c, -0.08));
      set('--ac-bronze-dk', shadeHex(c, -0.3));
      set('--bg-tabbar', shadeHex(c, 0.88));
    } else if ((theme as string) === 'facebook') {
      root.classList.add('theme-facebook');
    } else {
      root.classList.add('light', 'theme-light');
    }
  }, [theme, accentColor]);

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute('lang', language);
    root.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <ThemeContext.Provider value={{ theme, setTheme, language, setLanguage, accentColor, setAccentColor, t }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};
