import type { CRBook } from './types';

// Katameros — Daily Readings. Content generated by scripts/katameros/gen.ts
// from coptic.io (MIT) readings data; Psalm/Gospel verses embedded from our
// Bible text, epistles/Acts shown as references.

export const book: CRBook = {
  id: 'readings',
  title: { en: 'Katameros — Daily Readings', ar: 'القطمارس' },
  description: {
    en: 'The daily lectionary: Vespers, Matins and Liturgy readings — psalms, Gospels, Pauline and Catholic epistles and Acts — for every day of the Coptic year.',
    ar: 'القراءات اليومية: قراءات العشية وباكر والقداس — المزامير والأناجيل ورسائل بولس والكاثوليكون وأعمال الرسل — لكل يوم من أيام السنة القبطية.',
  },
  icon: 'CalendarDays',
  sections: [
    {
      id: 'sundays',
      title: { en: 'Sundays of the Year', ar: 'آحاد السنة' },
      documents: () => import('./readings-docs/days').then((m) => m.sundaysDocs),
    },
    {
      id: 'weekdays',
      title: { en: 'Weekday Readings', ar: 'قراءات أيام الأسبوع' },
      documents: () => import('./readings-docs/days').then((m) => m.weekdaysDocs),
    },
    {
      id: 'great-fast',
      title: { en: 'The Great Fast', ar: 'الصوم الكبير' },
      documents: () => import('./readings-docs/days').then((m) => m.fastDocs),
    },
    {
      id: 'feasts',
      title: { en: 'Feasts of the Lord', ar: 'أعياد السيد' },
      documents: () => import('./readings-docs/days').then((m) => m.feastsDocs),
    },
  ],
};
